'use strict';

// Runtime fragment extracted from config-page.js.
// The fragment is still generated by PKJS and executed inside the settings page.
module.exports = function buildRuntimeFragment() {
  return (
'function colorsFor(bgId, textId, accentId) {' +
'  return {' +
'    bg: hexFromByte(parseInt(document.getElementById(bgId).value, 10)),' +
'    text: hexFromByte(parseInt(document.getElementById(textId).value, 10)),' +
'    accent: hexFromByte(parseInt(document.getElementById(accentId).value, 10))' +
'  };' +
'}' +
'function dayColors() {' +
'  return colorsFor("customBgValue", "customTextValue", "customAccentValue");' +
'}' +
'function nightColors() {' +
'  return colorsFor("nightCustomBgValue", "nightCustomTextValue", "nightCustomAccentValue");' +
'}' +
// The color every font-picker preview (both the masked system-font
// images and the live Google-Fonts CSS text) paints itself in. This is
// deliberately NOT derived from the watch's own color scheme -- doing
// that used to make preview text/images render in whatever hue the
// day scheme's text role happened to be, which could turn barely
// legible against the picker's own background. It's the same neutral
// --text-strong the rest of this settings page's UI text already
// uses (see .font-picker-preview/-name's own CSS), so previews stay
// readable and consistent with the page's own light/dark theme
// (prefers-color-scheme) regardless of what the WATCH's day/night
// color scheme happens to be.
'function fontPreviewColor() {' +
'  return "var(--text-strong)";' +
'}' +

'function setSlotEditorColorGroupVisibility(contentVal) {' +
'  document.getElementById("slotEditColorGroup").style.display = (contentVal === "0") ? "none" : "flex";' +
'}' +
'function setSlotEditorColorButtons(value) {' +
'  SLOT_EDITOR_DRAFT_COLOR = parseInt(value, 10) || 0;' +
'  var buttons = document.getElementById("slotEditColorGroup").getElementsByClassName("mode-btn");' +
'  for (var i = 0; i < buttons.length; i++) {' +
'    buttons[i].className = "mode-btn" + (i === SLOT_EDITOR_DRAFT_COLOR ? " active" : "");' +
'  }' +
'}' +
'function slotEditorSelectColor(value) {' +
'  setSlotEditorColorButtons(value);' +
'}' +
'function updateColorRoleButtons(scheme) {' +
'  var colors = scheme === "night" ? nightColors() : dayColors();' +
'  var prefix = scheme === "night" ? "swatchNight" : "swatch";' +
'  document.getElementById(prefix + "Main").style.background = colors.text;' +
'  document.getElementById(prefix + "Accent").style.background = colors.accent;' +
'  document.getElementById(prefix + "Bg").style.background = colors.bg;' +
'  updateColorPresetTriggerLabel(scheme);' +
'}' +

'function mainColorPhrase(label) {' +
'  var idx = label.indexOf(",");' +
'  return idx === -1 ? label : label.substring(0, idx);' +
'}' +
'function accentColorName(label) {' +
'  var m = /,\\s*(.+?)\\s+accent$/.exec(label);' +
'  if (m) return m[1];' +
'  var m2 = /^(.+?)\\s+on\\s+/.exec(label);' +
'  return m2 ? m2[1] : label;' +
'}' +
// The one preset (if any) whose 3 colors exactly match the current
// ones -- null means none do, i.e. the current colors are genuinely
// custom. Used both to mark that one button "selected" in the popup
// and to decide what the trigger button itself should say.
'function updateColorPresetTriggerLabel(scheme) {' +
'  var colors = scheme === "night" ? nightColors() : dayColors();' +
'  var trigger = document.getElementById(scheme === "night" ? "nightSchemePresetTrigger" : "colorSchemePresetTrigger");' +
'  if (!trigger) return;' +
'  var mainLine = trigger.querySelector(".color-preset-main-line");' +
'  var accentLine = trigger.querySelector(".color-preset-accent-line");' +
'  trigger.style.background = colors.bg;' +
'  var matchId = matchingPresetId(colors);' +
'  if (matchId !== null) {' +
'    var preset = findPresetById(matchId);' +
'    if (mainLine) { mainLine.textContent = mainColorPhrase(preset.label); mainLine.style.color = preset.text; }' +
'    if (accentLine) { accentLine.textContent = accentColorName(preset.label) + " accent color"; accentLine.style.color = preset.accent; }' +
'  } else {' +
'    if (mainLine) { mainLine.textContent = "Custom: Main color on Background color"; mainLine.style.color = colors.text; }' +
'    if (accentLine) { accentLine.textContent = "Accent color"; accentLine.style.color = colors.accent; }' +
'  }' +
'}' +
'var CURRENT_PRESET_SCHEME = "day";' +
'function openColorPresetPicker(scheme) {' +
'  CURRENT_PRESET_SCHEME = scheme || "day";' +
'  document.getElementById("colorPresetPickerTitle").textContent = (scheme === "night") ? "Night color preset" : "Color preset";' +
'  renderColorPresetGrid();' +
'  document.getElementById("colorPresetPickerModal").className = "modal-overlay open";' +
'}' +
'function closeColorPresetPicker() {' +
'  document.getElementById("colorPresetPickerModal").className = "modal-overlay";' +
'}' +
// One button per COLOR_SCHEMES entry, colored in that preset\'s own
// background, plus one final "Custom" button (see this file\'s own
// request/comment above) showing whatever the current colors actually
// are -- not a separate footer action, just the last item in the same
// list. Re-run whenever the popup opens and whenever it matters which
// entry counts as "selected" -- which is only ever "which one, if any,
// matches the current colors", so there\'s nothing else to invalidate
// this on.
'function renderColorPresetGrid() {' +
'  var scheme = CURRENT_PRESET_SCHEME;' +
'  var colors = scheme === "night" ? nightColors() : dayColors();' +
'  var matchId = matchingPresetId(colors);' +
'  var html = "";' +
'  COLOR_SCHEMES.forEach(function (s) {' +
'    var selected = matchId !== null && String(matchId) === String(s.id);' +
'    html += \'<button type="button" class="color-preset-btn\' + (selected ? " selected" : "") + \'" style="background:\' + s.bg + \';" onclick="chooseColorPreset(\' + s.id + \')">\' +' +
'      \'<span class="color-preset-main-line" style="color:\' + s.text + \';">\' + esc(mainColorPhrase(s.label)) + "</span>" +' +
'      \'<span class="color-preset-accent-line" style="color:\' + s.accent + \';">\' + esc(accentColorName(s.label) + " accent color") + "</span></button>";' +
'  });' +
'  var customSelected = matchId === null;' +
'  html += \'<button type="button" class="color-preset-btn\' + (customSelected ? " selected" : "") + \'" style="background:\' + colors.bg + \';" onclick="chooseColorPreset(null)">\' +' +
'    \'<span class="color-preset-main-line" style="color:\' + colors.text + \';">Custom: Main color on Background color</span>\' +' +
'    \'<span class="color-preset-accent-line" style="color:\' + colors.accent + \';">Accent color</span></button>\';' +
'  document.getElementById("colorPresetPickerGrid").innerHTML = html;' +
'}' +
// null id means "Custom" was tapped -- same as tapping outside the
// popup, that just closes it without touching any colors (there\'s
// nothing to "apply" -- the current colors already are what they are).
'function chooseColorPreset(id) {' +
'  var scheme = CURRENT_PRESET_SCHEME;' +
'  closeColorPresetPicker();' +
'  if (id === null || id === undefined) return;' +
'  var preset = findPresetById(id);' +
'  document.getElementById(customHiddenIdFor("text", scheme)).value = hexToByte(preset.text);' +
'  document.getElementById(customHiddenIdFor("accent", scheme)).value = hexToByte(preset.accent);' +
'  document.getElementById(customHiddenIdFor("bg", scheme)).value = hexToByte(preset.bg);' +
'  updateColorRoleButtons(scheme);' +
'  if (scheme !== "night") updatePreview();' +
'}' +

'var CURRENT_PICKER_ROLE = null;' +
'var CURRENT_PICKER_SCHEME = "day";' +
'function openColorPicker(role, scheme) {' +
'  CURRENT_PICKER_ROLE = role;' +
'  CURRENT_PICKER_SCHEME = scheme || "day";' +
'  var titles = { text: "Pick main color", accent: "Pick accent color", bg: "Pick background color" };' +
'  document.getElementById("colorPickerTitle").textContent = titles[role] || "Pick a color";' +
'  renderHexColorGrid();' +
'  document.getElementById("colorPickerModal").className = "modal-overlay open";' +
'}' +
'function closeColorPicker() {' +
'  document.getElementById("colorPickerModal").className = "modal-overlay";' +
'  CURRENT_PICKER_ROLE = null;' +
'}' +
'function renderHexColorGrid() {' +
'  var container = document.getElementById("hexColorGrid");' +
'  container.innerHTML = "";' +
'  var hiddenId = customHiddenIdFor(CURRENT_PICKER_ROLE, CURRENT_PICKER_SCHEME);' +
'  var selected = parseInt(document.getElementById(hiddenId).value, 10);' +
'  var size = 15;' +
'  var centerX = 130, centerY = 127.5;' + // must match .hex-grid's fixed CSS width/height
'  function place(q, r) {' +
'    return {' +
'      x: centerX + size * Math.sqrt(3) * (q + r / 2),' +
'      y: centerY + size * 1.5 * r' +
'    };' +
'  }' +
'  for (var i = 0; i < PEBBLE_WHEEL_POSITIONS.length; i++) {' +
'    var pos = PEBBLE_WHEEL_POSITIONS[i];' +
'    var pt = place(pos.q, pos.r);' +
'    var sw = document.createElement("div");' +
'    sw.style.left = pt.x + "px";' +
'    sw.style.top = pt.y + "px";' +
'    sw.className = "hex-swatch" + (pos.b === selected ? " selected" : "");' +
'    sw.style.background = hexFromByte(pos.b);' +
'    sw.onclick = (function (byte) { return function () { pickColor(byte); }; })(pos.b);' +
'    container.appendChild(sw);' +
'  }' +
'  for (var j = 0; j < PEBBLE_WHEEL_HOLLOW.length; j++) {' +
'    var hp = PEBBLE_WHEEL_HOLLOW[j];' +
'    var hpt = place(hp.q, hp.r);' +
'    var hsw = document.createElement("div");' +
'    hsw.style.left = hpt.x + "px";' +
'    hsw.style.top = hpt.y + "px";' +
'    hsw.className = "hex-swatch hollow";' +
'    container.appendChild(hsw);' +
'  }' +
'}' +
'function pickColor(byte) {' +
'  if (!CURRENT_PICKER_ROLE) return;' +
'  var scheme = CURRENT_PICKER_SCHEME;' +
'  document.getElementById(customHiddenIdFor(CURRENT_PICKER_ROLE, scheme)).value = byte;' +
'  closeColorPicker();' +
'  updateColorRoleButtons(scheme);' +
'  if (scheme !== "night") updatePreview();' +
'}' +
'function onNightToggle() {' +
'  document.getElementById("nightSchemeSettings").style.display = document.getElementById("nightEnabled").checked ? "block" : "none";' +
'  updateSchemeActiveHighlight();' +
'}' +

// Rough "is it night" approximation for the day/night color highlight
// below -- a plain local-clock-hours check, not the watch\'s own real
// sun-altitude/civil-twilight test (get_active_color_scheme() in
// pebble-eclipse-watch.c), since that needs a location and a real
// astronomy calculation this page has no reason to duplicate just for
// a visual hint. Good enough to avoid the actual confusion this
// feature is for (editing colors that silently do nothing because
// they\'re not the active set right now) without claiming to be exact.
'function isNightNowApprox() {' +
'  var h = new Date().getHours();' +
'  return h < 6 || h >= 20;' +
'}' +
// Marks both day and night color subsections with which one is
// actually in effect right now (see .scheme-active-badge\'s own
// comment -- purely informational, nothing here is disabled): green
// "Active now" on the one in effect, red "Not active now" on the
// other. Only meaningful once night colors are actually turned on --
// with only one set of colors there\'s nothing to disambiguate, so
// both badges stay hidden.
'function updateSchemeActiveHighlight() {' +
'  var dayBadge = document.getElementById("daySchemeActiveBadge");' +
'  var nightBadge = document.getElementById("nightSchemeActiveBadge");' +
'  if (!document.getElementById("nightEnabled").checked) {' +
'    dayBadge.style.display = "none";' +
'    nightBadge.style.display = "none";' +
'    return;' +
'  }' +
'  var isNight = isNightNowApprox();' +
'  dayBadge.style.display = "";' +
'  nightBadge.style.display = "";' +
'  dayBadge.textContent = isNight ? "Not active now" : "Active now";' +
'  dayBadge.classList.toggle("inactive", isNight);' +
'  nightBadge.textContent = isNight ? "Active now" : "Not active now";' +
'  nightBadge.classList.toggle("inactive", !isNight);' +
'}' +

'function computeColorsSubheaderHtml() {' +
'  var nightEnabled = document.getElementById("nightEnabled").checked;' +
'  var label, colors;' +
'  if (!nightEnabled) {' +
'    label = "one set: ";' +
'    colors = dayColors();' +
'  } else if (isNightNowApprox()) {' +
'    label = "night mode: ";' +
'    colors = nightColors();' +
'  } else {' +
'    label = "day mode: ";' +
'    colors = dayColors();' +
'  }' +
'  function dot(hex) { return \'<span class="subhead-dot" style="background:\' + hex + \';"></span>\'; }' +
'  return esc(label) + dot(colors.text) + dot(colors.accent) + dot(colors.bg);' +
'}' + ''
// Mirrors save()\'s own edgeVal()/avail logic exactly (same
// computeSlotAvailability() call, same per-slot usable checks) so the
// count here can never disagree with what actually reaches the watch.
  );
};
