'use strict';

// Runtime fragment extracted from config-page.js.
// The fragment is still generated by PKJS and executed inside the settings page.
module.exports = function buildRuntimeFragment(context) {
  return (
'var MARKER_PREVIEW_IMAGES = ' + JSON.stringify(context.MARKER_PREVIEW_IMAGES) + ';' +
'var HAND_STYLE_IMAGES = ' + JSON.stringify(context.HAND_STYLE_IMAGES) + ';' +
'var MARKER_PRESET_IMAGES = ' + JSON.stringify(context.MARKER_PRESET_IMAGES) + ';' +
'var HAND_STYLE_DIAGRAM_IMAGES = ' + JSON.stringify(context.HAND_STYLE_DIAGRAM_IMAGES) + ';' +
'var HAND_STYLE_ICON_IMAGES = ' + JSON.stringify(context.HAND_STYLE_ICON_IMAGES) + ';' +
'var WEATHER_ICON_STYLE_PREVIEWS = ' + JSON.stringify(context.WEATHER_ICON_STYLE_PREVIEWS) + ';' +
// Matches weather_icon_style\'s own <option> list exactly.
'var WEATHER_ICON_STYLE_NAMES = ["Simple", "Hollow", "Full color"];' +
// Matches the Shape <option> list\'s own order/values exactly (see
// handEditorModalHtml() and STYLE_IDS_BY_NAME in
// scripts/generate-hand-style-icons.js).
'var HAND_STYLE_NAMES = ["Baton", "Galba", "Pencil", "Dauphine", "Sword", "Pomme", "Spade", "Arrow", "Leaf", "Syringe", "Serpentine"];' +
// EXAMPLE_STYLE_PRESETS is { title, description, preset } per slot
// (or null for an empty one) -- the popup below reads title/
// description directly, and applies `.preset` (the same shape
// applyStyleCornersJson() everywhere else already expects) only once
// the user actually taps "Apply this style". EXAMPLE_STYLE_IMAGES is
// needed client-side too now, for the popup's own <img> -- each
// button's own <img src> above is a separate, already-baked-in copy.
'var EXAMPLE_STYLE_PRESETS = ' + JSON.stringify(context.EXAMPLE_STYLE_PRESETS) + ';' +
'var EXAMPLE_STYLE_IMAGES = ' + JSON.stringify(context.EXAMPLE_STYLE_IMAGES) + ';' +
'var s_exampleStyleModalSlot = null;' +
'function toggleManual() {' +
'  var on = !document.getElementById("autoLoc").checked;' +
'  document.getElementById("lat").disabled = !on;' +
'  document.getElementById("lon").disabled = !on;' +
'  document.getElementById("locationSearch").disabled = !on;' +
'  document.getElementById("locationSearchBtn").disabled = !on;' +
'}' +
'function toggleTestMode() {' +
'  document.getElementById("testDateTime").disabled = !document.getElementById("testMode").checked;' +
'}' +
// Loads raw message log entry `i` (index into rawMessageLogJson, same
// oldest-first order rawMessageLogButtonsHtml() built its button ids
// from) into the debugData textarea, and highlights the button that
// was tapped.
'function shortNameFromAddress(addr) {' +
'  if (!addr) return "";' +
'  var place = addr.city || addr.town || addr.village || addr.municipality || addr.county || addr.state || "";' +
'  var country = addr.country || "";' +
'  if (place && country) return place + ", " + country;' +
'  return place || country;' +
'}' +
// Coordinates just changed by hand -- the cached name (if any) no
// longer necessarily matches them, so clear it rather than let a
// now-stale "Use Innsbruck, Austria" linger over different
// coordinates; onManualCoordsBlur() below re-resolves it once typing
// stops, same "don\'t look it up on every keystroke" reasoning as not
// re-fetching on every settings page load.
'function onManualCoordsInput() {' +
'  var el = document.getElementById("locationName");' +
'  if (el) el.value = "";' +
'}' +
'function onManualCoordsBlur() {' +
'  if (!document.getElementById("autoLoc").checked && !document.getElementById("locationName").value) {' +
'    reverseGeocodeAndCacheLocationName();' +
'  }' +
'}' +
// One-shot reverse geocode of whatever\'s currently in #lat/#lon into
// #locationName (see that hidden field\'s own comment) -- called once
// at page init if a name isn\'t already cached (see the bottom of this
// script) and again from onManualCoordsBlur() above after a manual
// coordinate edit. Silently does nothing on failure/no results,
// leaving the Location sub-header to fall back to raw coordinates --
// this is a "nice to have" label, not something worth surfacing an
// error for.
'function reverseGeocodeAndCacheLocationName() {' +
'  var lat = document.getElementById("lat").value;' +
'  var lon = document.getElementById("lon").value;' +
'  if (!lat || !lon) return;' +
'  var xhr = new XMLHttpRequest();' +
'  xhr.open("GET", "https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=" + encodeURIComponent(lat) + "&lon=" + encodeURIComponent(lon) + "&zoom=10&addressdetails=1", true);' +
'  xhr.timeout = 8000;' +
'  xhr.onload = function () {' +
'    try {' +
'      var data = JSON.parse(xhr.responseText);' +
'      var name = shortNameFromAddress(data && data.address);' +
'      if (name) {' +
'        document.getElementById("locationName").value = name;' +
'        refreshAllSectionSubheaders();' +
'      }' +
'    } catch (e) {}' +
'  };' +
'  xhr.send();' +
'}' +
'function searchLocation() {' +
'  var query = document.getElementById("locationSearch").value;' +
'  query = query ? query.trim() : "";' +
'  if (!query) return;' +
'  var statusEl = document.getElementById("locationSearchStatus");' +
'  statusEl.textContent = "Searching...";' +
'  var xhr = new XMLHttpRequest();' +
'  xhr.open("GET", "https://nominatim.openstreetmap.org/search?format=json&limit=1&addressdetails=1&q=" + encodeURIComponent(query), true);' +
'  xhr.timeout = 8000;' +
'  xhr.onload = function () {' +
'    try {' +
'      var results = JSON.parse(xhr.responseText);' +
'      if (results && results.length > 0) {' +
'        document.getElementById("lat").value = parseFloat(results[0].lat).toFixed(5);' +
'        document.getElementById("lon").value = parseFloat(results[0].lon).toFixed(5);' +
'        document.getElementById("locationName").value = shortNameFromAddress(results[0].address) || query;' +
'        statusEl.textContent = "Found: " + (results[0].display_name || query);' +
'        refreshAllSectionSubheaders();' +
'      } else {' +
'        statusEl.textContent = "No results found.";' +
'      }' +
'    } catch (e) {' +
'      statusEl.textContent = "Search failed.";' +
'    }' +
'  };' +
'  xhr.onerror = function () { statusEl.textContent = "Network error."; };' +
'  xhr.ontimeout = function () { statusEl.textContent = "Timed out."; };' +
'  xhr.send();' +
'}' +

'function packedByteFor(r2,g2,b2) { return 0xC0 | (r2<<4) | (g2<<2) | b2; }' +
'function chHex(v) { var h = (v*85).toString(16); return h.length<2 ? "0"+h : h; }' +
'function hexFor(r2,g2,b2) { return "#" + chHex(r2) + chHex(g2) + chHex(b2); }' +
'function hexFromByte(byte) { return hexFor((byte>>4)&3, (byte>>2)&3, byte&3); }' +

// Runtime copy of the generator-side COLOR_SCHEMES table -- serialized
// straight from that same array at page-generation time, same "can't
// drift apart" reasoning as FONT_LOOKUP's own runtime copy. Shared by
// findPresetById() below and the color preset picker popup further
// down (matchingPresetId()/renderColorPresetGrid()).
'var COLOR_SCHEMES = ' + JSON.stringify(context.COLOR_SCHEMES) + ';' +

'function esc(str) {' +
'  return String(str == null ? "" : str).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");' +
'}' +

// Runtime copy of the generator-side FONT_LOOKUP table (see its own
// comment there for what each field means) -- serialized straight
// from that same array at page-generation time, not hand-duplicated,
// so the two can never drift apart the way two independently-typed
// copies could.
'var FONT_LOOKUP = ' + JSON.stringify(context.FONT_LOOKUP) + ';' +
// Runtime copy of the constant controlling how many "Example styles"
// tiles exist -- used only by the Example styles section's own
// sub-header (computeExamplesSubheader() below); that count never
// changes at runtime, so this is just a plain baked-in number, same
// spirit as every other "generator-side data, copied once for the
// browser" constant on this page.
'var EXAMPLE_STYLE_COUNT = ' + context.EXAMPLE_STYLE_COUNT + ';' +
// Same reasoning as FONT_LOOKUP just above -- serialized straight from
// the generator-side FONT_PREVIEW_IMAGES (itself just require()'d from
// the generated src/pkjs/font-preview-images.js) rather than
// hand-duplicated. Empty ({}) whenever no font-preview PNGs have been
// added yet -- every lookup against it below already handles that
// gracefully.
'var FONT_PREVIEW_IMAGES = ' + JSON.stringify(context.FONT_PREVIEW_IMAGES) + ';' +
'function drawSkyLayer(ctx, x, y, w, h) {' +
'  var grad = ctx.createLinearGradient(0, y, 0, y + h);' +
'  grad.addColorStop(0, "#4a90d9");' +
'  grad.addColorStop(1, "#bfe3f5");' +
'  ctx.fillStyle = grad;' +
'  ctx.fillRect(x, y, w, h);' +
'  ctx.beginPath();' +
'  ctx.arc(x + w * 0.72, y + h * 0.2, Math.max(7, w * 0.09), 0, 2 * Math.PI);' +
'  ctx.fillStyle = "#fff6d0";' +
'  ctx.fill();' +
'  ctx.fillStyle = "rgba(255,255,255,0.9)";' +
'  function puff(cx, cy, r) { ctx.beginPath(); ctx.arc(cx, cy, r, 0, 2 * Math.PI); ctx.fill(); }' +
'  var cy = y + h * 0.6;' +
'  puff(x + w * 0.22, cy, w * 0.08);' +
'  puff(x + w * 0.32, cy - 3, w * 0.1);' +
'  puff(x + w * 0.42, cy, w * 0.07);' +
'}' +

// CORNER_PREVIEW_LABELS is now derived client-side from the same
// CORNER_CATEGORIES injection categoryForContentId()/findCategory()
// use, right after that injection below -- see presets-lookups.js's
// own header comment for why one shared array replaced this and 2
// other independently hand-maintained lists.

'function hasPreviewContent(contentId) {' +
'  var el = document.getElementById(contentId);' +
'  if (!el) return false;' +
'  var v = parseInt(el.value, 10);' +
'  return v !== 0 && !!CORNER_PREVIEW_LABELS[v];' +
'}' +

'function drawCornersAndEdges(ctx, w, h, colors, skyBottom) {' +
'  var bottomY = (typeof skyBottom === "number") ? skyBottom : h;' +
'  var lineH = 14;' +
'  if (slotAvailable("cornerTLWrap")) drawCornerSlot(ctx, "cornerTL", "cornerTLColor", 5, 5, "left", colors);' +
'  if (slotAvailable("cornerTRWrap")) drawCornerSlot(ctx, "cornerTR", "cornerTRColor", w - 5, 5, "right", colors);' +
'  if (slotAvailable("cornerBLWrap")) drawCornerSlot(ctx, "cornerBL", "cornerBLColor", 5, bottomY - 14, "left", colors);' +
'  if (slotAvailable("cornerBRWrap")) drawCornerSlot(ctx, "cornerBR", "cornerBRColor", w - 5, bottomY - 14, "right", colors);' +
'  var needMiddleMargins = slotAvailable("upperMiddleWrap") || slotAvailable("bottomMiddleWrap") || slotAvailable("middleLeftWrap") || slotAvailable("middleRightWrap");' +
'  var mm = needMiddleMargins ? computeMiddleFeatureMargins(w, h) : null;' +
'  if (slotAvailable("upperMiddleWrap")) {' +
'    var upperHasLine2 = hasPreviewContent("upperMiddleLine2Content");' +
'    drawCornerSlot(ctx, "upperMiddleLine1Content", "upperMiddleLine1Color", w / 2, upperHasLine2 ? mm.top : mm.top + lineH / 2, "center", colors);' +
'    if (upperHasLine2) drawCornerSlot(ctx, "upperMiddleLine2Content", "upperMiddleLine2Color", w / 2, mm.top + lineH, "center", colors);' +
'  }' +
'  if (slotAvailable("bottomMiddleWrap")) {' +
'    var bottomHasLine2 = hasPreviewContent("bottomMiddleLine2Content");' +
'    drawCornerSlot(ctx, "bottomMiddleLine1Content", "bottomMiddleLine1Color", w / 2, bottomHasLine2 ? bottomY - mm.bottom - lineH : bottomY - mm.bottom - lineH / 2, "center", colors);' +
'    if (bottomHasLine2) drawCornerSlot(ctx, "bottomMiddleLine2Content", "bottomMiddleLine2Color", w / 2, bottomY - mm.bottom, "center", colors);' +
'  }' +
'  if (slotAvailable("middleLeftWrap")) {' +
'    var midLeftHasLine2 = hasPreviewContent("middleLeftLine2Content");' +
'    drawCornerSlot(ctx, "middleLeftLine1Content", "middleLeftLine1Color", mm.left, midLeftHasLine2 ? h / 2 - 4 - lineH / 2 : h / 2 - 4, "left", colors);' +
'    if (midLeftHasLine2) drawCornerSlot(ctx, "middleLeftLine2Content", "middleLeftLine2Color", mm.left, h / 2 - 4 + lineH / 2, "left", colors);' +
'  }' +
'  if (slotAvailable("middleRightWrap")) {' +
'    var midRightHasLine2 = hasPreviewContent("middleRightLine2Content");' +
'    drawCornerSlot(ctx, "middleRightLine1Content", "middleRightLine1Color", w - mm.right, midRightHasLine2 ? h / 2 - 4 - lineH / 2 : h / 2 - 4, "right", colors);' +
'    if (midRightHasLine2) drawCornerSlot(ctx, "middleRightLine2Content", "middleRightLine2Color", w - mm.right, h / 2 - 4 + lineH / 2, "right", colors);' +
'  }' +
'}' +

// ---- hand preview geometry --------------------------------------------
// A direct port of hand_layer.c's compute_hand_geometry_fp() (and the
// draw passes around it) from the watch's own fixed-point trig into
// plain floating-point canvas math -- there\'s no fixed-point precision
// need here the way the watch has, so every SUBPIXEL_BITS/int64 step
// over there is just its equivalent float multiply/sin/cos here. Kept
// in the exact same per-style order/shape as compute_hand_geometry_fp()
// so the two stay easy to compare side by side; see that function\'s
// own per-style comments in hand_layer.c for what each shape/field
// combination actually means -- not re-explained per style here.
//
// angle is in radians, same clockwise-from-12 convention already used
// elsewhere on this page (see hourAngle/minAngle below): x = cx +
// axial*sin(angle), y = cy - axial*cos(angle), matching
// point_at_axial_fp()\'s own dx/dy exactly.
'function hexToRgb(hex) {' +
'  var m = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex || "");' +
'  if (!m) return { r: 0, g: 0, b: 0 };' +
'  return { r: parseInt(m[1], 16), g: parseInt(m[2], 16), b: parseInt(m[3], 16) };' +
'}' +
// Recolors an offscreen copy of the image by directly rewriting pixel
// RGB values while leaving each pixel\'s own alpha untouched -- unlike
// relying on globalCompositeOperation (which isn\'t consistently
// supported across the range of embedded WebViews Pebble phones
// actually ship), this works the same everywhere and mirrors exactly
// what the watch\'s own tint_marker_bitmap() does. Cached per
// style+color combination since it\'s real per-pixel work and the
// preview redraws roughly once a second.
'var MARKER_TINT_CACHE = {};' +
'function pointOnRing(cx, cy, w, h, angle, pct, eccentricityPct) {' +
'  var sinV = Math.sin(angle), cosV = Math.cos(angle);' +
'  var reach = markerReach(w, h, pct);' +
'  var circlePt = { x: cx + reach * sinV, y: cy - reach * cosV };' +
'  if (!eccentricityPct) return circlePt;' +
'  var hw = w / 2, hh = h / 2, reachMax = Math.max(hw, hh);' +
'  var rectHw = reach * hw / reachMax, rectHh = reach * hh / reachMax;' +
'  var adx = Math.abs(sinV), ady = Math.abs(cosV);' +
'  var tx = adx === 0 ? Infinity : rectHw / adx, ty = ady === 0 ? Infinity : rectHh / ady;' +
'  var t = Math.min(tx, ty);' +
'  var rectPt = { x: cx + t * sinV, y: cy - t * cosV };' +
'  return {' +
'    x: circlePt.x + (rectPt.x - circlePt.x) * eccentricityPct / 100,' +
'    y: circlePt.y + (rectPt.y - circlePt.y) * eccentricityPct / 100' +
'  };' +
'}' +
// Direct port of draw_ring_mark_fp(): a straight quad from inner to
// outer, halfThick wide, with the requested cap style -- 0=dot (round,
// via circles at both ends), 1=line (flush ends), 2=square (ends
// extended outward by halfThick, like stroke-linecap:square).
'function romanNumeral(num) {' +
'  if (num <= 0) return String(num);' +
'  var VALUES = [50, 40, 10, 9, 5, 4, 1], SYMBOLS = ["L", "XL", "X", "IX", "V", "IV", "I"];' +
'  var out = "";' +
'  for (var i = 0; i < VALUES.length && num > 0; i++) { while (num >= VALUES[i]) { out += SYMBOLS[i]; num -= VALUES[i]; } }' +
'  return out;' +
'}' +
'function drawBigAnalogPreview(ctx, colors, now, showSeconds, w, h, markerImageDrawn) {' +
'  var cx = w / 2, cy = h / 2;' +
'  var scale = w / 200;' + // every hand/shadow dimension below is a real on-watch px value (200x228 screen) -- see readHandConfig()'s own comment
'  var markerStyle = parseInt(document.getElementById("bigAnalogMarkerStyle").value, 10);' +

'  if (markerStyle <= 2) {' +
'    var idx = markerStyle;' +
'    drawMarkerRing(ctx, cx, cy, w, h, MARKER_STYLE_SECOND_PRESETS[idx], 60, 5, colors);' +
'    drawMarkerRing(ctx, cx, cy, w, h, MARKER_STYLE_HOUR_PRESETS[idx], 12, 0, colors);' +
'  } else if (markerStyle === 8) {' +
'    var secCfg = readCustomMarkerConfig("sec"), hourCfg = readCustomMarkerConfig("hour");' +
'    drawMarkerRing(ctx, cx, cy, w, h, secCfg, 60, 5, colors);' +
'    drawMarkerRing(ctx, cx, cy, w, h, hourCfg, 12, 0, colors);' +
'    drawTextMarkers(ctx, cx, cy, w, h, colors);' +
'  } else if (markerStyle === 9) {' +
'    /* none -- no marker ring, no placeholder text either */' +
'  } else if (!markerImageDrawn) {' +
'    ctx.font = "10px sans-serif";' +
'    ctx.fillStyle = colors.text;' +
'    ctx.textAlign = "center"; ctx.textBaseline = "middle";' +
'    ctx.fillText("(bitmap markers)", cx, 12);' +
'  }' +

'  var hh = now.getHours() % 12, mm = now.getMinutes(), ss = now.getSeconds();' +
'  var hourAngle = ((hh * 60 + mm) / 720) * 2 * Math.PI;' +
'  var minAngle = (mm / 60) * 2 * Math.PI;' +
'  var secAngle = (ss / 60) * 2 * Math.PI;' +
'  var shadowAngleDeg = parseFloat(document.getElementById("shadowAngle").value) || 0;' +
'  var shadowTranslucentStyle = document.getElementById("shadowTranslucent").value !== "false";' +
'  drawHandFull(ctx, cx, cy, hourAngle, readHandConfig("hour", scale), colors, shadowAngleDeg, shadowTranslucentStyle);' +
'  drawHandFull(ctx, cx, cy, minAngle, readHandConfig("min", scale), colors, shadowAngleDeg, shadowTranslucentStyle);' +
'  if (showSeconds) {' +
'    drawHandFull(ctx, cx, cy, secAngle, readHandConfig("sec", scale), colors, shadowAngleDeg, shadowTranslucentStyle);' +
'  }' +

'  var ccRadius = (parseFloat(document.getElementById("centerCircleRadius").value) || 0) * scale;' +
'  if (ccRadius > 0) {' +
'    var ccColor = resolveHandPreviewColor(document.getElementById("centerCircleColor").value, colors) || colors.text;' +
'    ctx.fillStyle = ccColor;' +
'    ctx.beginPath(); ctx.arc(cx, cy, ccRadius, 0, 2 * Math.PI); ctx.fill();' +
'  }' +
'}' +

'function drawDigitalPreview(ctx, colors, now, showSeconds, w, panelTop, panelBottom) {' +
'  var fontSel = document.getElementById("clockFont");' +
'  var opt = fontSel.options[fontSel.selectedIndex];' +
'  var hh = now.getHours(), mm = now.getMinutes();' +
'  var txt = (hh < 10 ? "0" : "") + hh + ":" + (mm < 10 ? "0" : "") + mm;' +
'  if (showSeconds) { var ss = now.getSeconds(); txt += ":" + (ss < 10 ? "0" : "") + ss; }' +
'  ctx.font = canvasFontFor(opt.getAttribute("data-preview") || "", 26);' +
'  ctx.fillStyle = colors.text;' +
'  ctx.textAlign = "center"; ctx.textBaseline = "middle";' +
'  ctx.fillText(txt, w / 2, panelTop + (panelBottom - panelTop) * 0.42);' +
'  ctx.font = "11px sans-serif";' +
'  ctx.fillText(now.toDateString(), w / 2, panelBottom - 12);' +
'}' +

'function updatePreview() {' +
'  var canvas = document.getElementById("previewCanvas");' +
'  if (!canvas || !canvas.getContext) return;' +
'  var ctx = canvas.getContext("2d");' +
'  var w = canvas.width, h = canvas.height;' +
'  ctx.clearRect(0, 0, w, h);' +

'  var colors = dayColors();' +
'  var styleVal = document.getElementById("bottomStyleValue").value;' +
'  var now = new Date();' +
'  var secondsBox = document.getElementById("showSeconds");' +
'  var showSeconds = secondsBox.checked && !secondsBox.disabled;' +

'  if (styleVal === "analog") {' +
'    drawSkyLayer(ctx, 0, 0, w, h);' +
'    var markerStyleVal = document.getElementById("bigAnalogMarkerStyle").value;' +
'    var markerStyleInt = parseInt(markerStyleVal, 10);' +
'    var markerImageDrawn = (markerStyleInt >= 3 && markerStyleInt !== 8 && markerStyleInt !== 9) && drawTintedMarkerBitmap(ctx, markerStyleVal, w, h, colors.text);' +
'    drawBigAnalogPreview(ctx, colors, now, showSeconds, w, h, markerImageDrawn);' +
'    drawCornersAndEdges(ctx, w, h, colors, h);' +
'  } else {' +
'    var skyH = Math.round(h * 152 / 228);' +
'    drawSkyLayer(ctx, 0, 0, w, skyH);' +
'    drawCornersAndEdges(ctx, w, h, colors, skyH);' +
'    ctx.fillStyle = colors.bg;' +
'    ctx.fillRect(0, skyH, w, h - skyH);' +
'    drawDigitalPreview(ctx, colors, now, showSeconds, w, skyH, h);' +
'  }' +
'}' +

'function onBottomStyleChange() {' +
'  var styleVal = document.getElementById("bottomStyleValue").value;' +
'  var isAnalog = styleVal === "analog";' +
'  document.getElementById("digitalOnlySettings").style.display = (styleVal === "digital") ? "block" : "none";' +
'  document.getElementById("bigAnalogSettings").style.display = isAnalog ? "block" : "none";' +
'  updateDigitalSidesVisibility();' +
'  var secondsBox = document.getElementById("showSeconds");' +
'  var fontSel = document.getElementById("clockFont");' +
'  var opt = fontSel.options[fontSel.selectedIndex];' +
'  var fontOk = opt.getAttribute("data-seconds") === "1";' +
'  var secondsUnavailable = !isAnalog && !fontOk;' +
'  secondsBox.disabled = secondsUnavailable;' +
'  if (secondsUnavailable) secondsBox.checked = false;' +
'  document.getElementById("secondsHelp").style.display = secondsUnavailable ? "block" : "none";' +
'  renderSlotPicker();' +
'  updatePreview();' +
'}' +
// A font switch can turn side features on/off (the "too wide" check
// depends on the clock font, not just digital-vs-analog), so both this
// and onBottomStyleChange() above call it. If the newly-selected font
// can't support them, forces digitalSides back to "none" -- same
// reasoning clearGrayedSlotsIfUnavailable() clears stale corner/edge picks
// instead of leaving a hidden section quietly keep sending a value the
// watch would otherwise still draw.
'function updateDigitalSidesVisibility() {' +
'  var styleVal = document.getElementById("bottomStyleValue").value;' +
'  var fontSel = document.getElementById("clockFont");' +
'  var opt = fontSel.options[fontSel.selectedIndex];' +
'  var fontIsWide = opt.getAttribute("data-wide") === "1";' +
'  var isDigital = styleVal === "digital";' +
'  document.getElementById("digitalSidesSection").style.display = (isDigital && !fontIsWide) ? "" : "none";' +
'  document.getElementById("digitalSidesWideHelp").style.display = (isDigital && fontIsWide) ? "" : "none";' +
'  if (!isDigital || fontIsWide) {' +
'    document.getElementById("digitalSides").value = "none";' +
'    var buttons = document.getElementById("digitalSidesGroup").getElementsByClassName("mode-btn");' +
'    for (var i = 0; i < buttons.length; i++) buttons[i].className = "mode-btn";' +
'  }' +
'}' +
'function toggleDigitalSide(side) {' +
'  var hidden = document.getElementById("digitalSides");' +
'  var cur = hidden.value;' +
'  var leftOn = cur === "left" || cur === "both";' +
'  var rightOn = cur === "right" || cur === "both";' +
'  if (side === "left") leftOn = !leftOn; else rightOn = !rightOn;' +
'  var next = leftOn && rightOn ? "both" : (leftOn ? "left" : (rightOn ? "right" : "none"));' +
'  hidden.value = next;' +
'  var buttons = document.getElementById("digitalSidesGroup").getElementsByClassName("mode-btn");' +
'  buttons[0].className = "mode-btn" + (leftOn ? " active" : "");' +
'  buttons[1].className = "mode-btn" + (rightOn ? " active" : "");' +
'  renderSlotPicker();' +
'  updatePreview();' +
'}' +
// Runtime copy of presets-lookups.js's own CORNER_CATEGORIES --
// serialized straight from that same canonical array (already
// filtered for the current auroraEnabled state -- see
// cornerCategoriesForClient above) rather than hand-duplicated, same
// pattern as FONT_LOOKUP/COLOR_SCHEMES above. CORNER_PREVIEW_LABELS
// (used by hasPreviewContent()/drawCornerSlot() below) is derived from
// it too, right after, instead of being its own separately-maintained
// list -- see presets-lookups.js's own header comment for why one
// shared array now covers what used to be 3 independently hand-typed
// ones (a flat id+label list, a category-grouped id+label copy, and a
// separate id->preview-text map) that could, and did, drift apart.
'var CONTENT_SELECT_IDS = ["cornerTL", "cornerTR", "cornerBL", "cornerBR", ' +
'  "upperMiddleLine1Content", "upperMiddleLine2Content", "bottomMiddleLine1Content", "bottomMiddleLine2Content", ' +
'  "middleLeftLine1Content", "middleLeftLine2Content", "middleRightLine1Content", "middleRightLine2Content"];' +
'var CORNER_CATEGORIES = ' + JSON.stringify(context.cornerCategoriesForClient) + ';' +
'var CORNER_PREVIEW_LABELS = {};' +
'CORNER_CATEGORIES.forEach(function (cat) {' +
'  cat.items.forEach(function (it) {' +
'    if (it.preview) CORNER_PREVIEW_LABELS[it.id] = it.preview;' +
'  });' +
'});' +
'function updateWeatherIconStyleVisibility() {' +
'  updateWeatherIconStyleTriggerLabel();' +
'}' +

// ---- collapsible sections + slider step buttons ------------------------
'function toggleSection(id) {' +
'  var body = document.getElementById("section-" + id);' +
'  var chev = document.getElementById("chev-" + id);' +
'  var sub = document.getElementById("subhead-" + id);' +
'  if (!body) return;' +
'  var isOpen = body.style.display !== "none";' +
'  body.style.display = isOpen ? "none" : "";' +
'  if (chev) chev.className = isOpen ? "chevron" : "chevron open";' +
// The sub-header is only useful while collapsed (a quick summary of
// what\'s inside); once the section\'s own full controls are visible
// it\'s redundant, so it disappears on expansion per the request --
// its text stays computed underneath (refreshAllSectionSubheaders()
// keeps updating it even while hidden), just not shown.
'  if (sub) sub.style.display = isOpen ? "" : "none";' +
'}' +
'function stepSlider(id, delta) {' +
'  var el = document.getElementById(id);' +
'  if (!el) return;' +
'  var min = parseFloat(el.min), max = parseFloat(el.max);' +
'  var v = parseFloat(el.value) + delta;' +
'  if (!isNaN(min) && v < min) v = min;' +
'  if (!isNaN(max) && v > max) v = max;' +
'  el.value = v;' +
'  if (el.oninput) el.oninput();' +
'  else if (el.onchange) el.onchange();' +
'}' +

// Press-and-hold repeat for the +/- slider step buttons. Reads the
// button's own onclick="stepSlider(\'id\', delta)" text to find which
// slider and direction it steps, rather than needing separate
// data attributes on all 20-odd call sites above -- one generic
// listener covers all of them, present and future. A single tap is
// left to the browser's normal click (one call to stepSlider); this
// only starts repeating after a short delay, so a quick tap never
// double-steps.
'var SLIDER_HOLD_TIMER = null;' +
'var SLIDER_HOLD_INTERVAL = null;' +
'function parseStepSliderArgs(btn) {' +
'  var attr = btn.getAttribute("onclick") || "";' +
'  var m = attr.match(/stepSlider\\(\'([^\']+)\',\\s*(-?\\d+)\\)/);' +
'  return m ? { id: m[1], delta: parseInt(m[2], 10) } : null;' +
'}' +
'function stopSliderHold() {' +
'  if (SLIDER_HOLD_TIMER) { clearTimeout(SLIDER_HOLD_TIMER); SLIDER_HOLD_TIMER = null; }' +
'  if (SLIDER_HOLD_INTERVAL) { clearInterval(SLIDER_HOLD_INTERVAL); SLIDER_HOLD_INTERVAL = null; }' +
'}' +
'function startSliderHold(btn) {' +
'  var args = parseStepSliderArgs(btn);' +
'  if (!args) return;' +
'  stopSliderHold();' +
'  SLIDER_HOLD_TIMER = setTimeout(function () {' +
'    SLIDER_HOLD_INTERVAL = setInterval(function () { stepSlider(args.id, args.delta); }, 90);' +
'  }, 400);' +
'}' +
'document.addEventListener("mousedown", function (e) {' +
'  var btn = e.target.closest && e.target.closest(".slider-step-btn");' +
'  if (btn) { startSliderHold(btn); e.preventDefault(); }' + // belt-and-suspenders alongside the CSS
                                                                // user-select:none above -- stops the
                                                                // press-and-hold repeat from also
                                                                // starting a text selection drag
'});' +
'document.addEventListener("touchstart", function (e) {' +
'  var btn = e.target.closest && e.target.closest(".slider-step-btn");' +
'  if (btn) startSliderHold(btn);' +
'}, { passive: true });' +
'["mouseup", "mouseleave", "touchend", "touchcancel"].forEach(function (ev) {' +
'  document.addEventListener(ev, stopSliderHold);' +
'});' +

'function onBitmapCornerOverrideChange() {' +
'  clearGrayedSlotsIfUnavailable();' +
'  renderSlotPicker();' +
'  updatePreview();' +
'}' +

// ---- custom hour/seconds indices popups --------------------------------
'var CM_FIELDS = ["Style", "Thickness", "InnerEcc", "OuterEcc", "InnerBorder", "OuterBorder", "Translucent", "Color"];' +
'var CM_CHECKBOX_FIELDS = ["Translucent"];' +
'function cmHiddenPrefix(kind) { return kind === "hour" ? "customHour" : "customSec"; }' +
'function cmPopupPrefix(kind) { return kind === "hour" ? "cmHour" : "cmSec"; }' +
'var MARKER_PRESETS = {' +
'  hour: {' +
'    minimal: { Style: "1", Thickness: "1", InnerEcc: "0", OuterEcc: "0", InnerBorder: "20", OuterBorder: "100" },' +
'    small:   { Style: "1", Thickness: "1", InnerEcc: "0", OuterEcc: "0", InnerBorder: "0", OuterBorder: "100" },' +
'    big:     { Style: "2", Thickness: "3", InnerEcc: "0", OuterEcc: "0", InnerBorder: "0", OuterBorder: "100" }' +
'  },' +
'  sec: {' +
'    minimal: { Style: "0", Thickness: "1", InnerEcc: "0", OuterEcc: "0", InnerBorder: "85", OuterBorder: "100" },' +
'    small:   { Style: "1", Thickness: "1", InnerEcc: "0", OuterEcc: "0", InnerBorder: "60", OuterBorder: "100" },' +
'    big:     { Style: "1", Thickness: "1", InnerEcc: "0", OuterEcc: "0", InnerBorder: "60", OuterBorder: "100" }' +
'  }' +
'};' +
// A rough approximation of the 3 built-in procedural styles, translated
// into border-reach percentages (see marker_reach_px() in
// marker_layer.c) now that a mark's length comes directly from its
// inner/outer border points rather than a separate slider -- a starting
// point to tune from, not an exact match. The "second" ring has no real
// minimal-style equivalent (that style draws no second indices at all),
// so its "minimal" preset is just a short stub near the outer edge.
'function openCenterCircleEditor() {' +
'  document.getElementById("centerCircleModal").className = "modal-overlay open";' +
'}' +
'function closeCenterCircleEditor() {' +
'  document.getElementById("centerCircleModal").className = "modal-overlay";' +
'}' +
'function openShadowStyleEditor() {' +
'  document.getElementById("shadowStyleModal").className = "modal-overlay open";' +
'}' +
'function closeShadowStyleEditor() {' +
'  document.getElementById("shadowStyleModal").className = "modal-overlay";' +
'}' +
'function heHiddenPrefix(kind) { return kind === "hour" ? "handHour" : (kind === "min" ? "handMin" : "handSec"); }' +
'function hePopupPrefix(kind) { return "he" + kind.charAt(0).toUpperCase() + kind.slice(1); }' +
// Runtime copy of presets-lookups.js's own HAND_PRESETS -- serialized
// straight from that same canonical object (see resources/infographics/
// hands<n>.png, embedded via scripts/generate-infographics.js as
// HAND_STYLE_IMAGES, for the matching preview images) rather than
// hand-duplicated, same pattern as FONT_LOOKUP/COLOR_SCHEMES above.
// Keyed "1".."9" to match those filenames, each with a display title
// plus hour/min/sec field sets in the same shape applyHandPresetToKind()
// below writes into the hidden custom-hand inputs, PLUS a centerCircle
// and shadow field set applied the same way to the standalone Center
// circle/Shadow style settings (see applyHandPresetExtras() below) --
// those two aren't per-hand, but still look like part of "the hand
// style" to anyone picking a preset, so a preset now sets them too
// instead of leaving whatever was there before. Picking a preset is a
// one-shot copy into those same fields the manual "Edit ... hand" /
// Center circle / Shadow style editors use -- nothing about it is
// remembered as a distinct "preset" afterward, on this page or on the
// watch (see hand_layer.h's own comment for why the watch doesn't need
// to know).
'var HAND_PRESETS = ' + JSON.stringify(context.HAND_PRESETS) + ';' +
'function onShadowAngleInput() {' +
'  var el = document.getElementById("shadowAngle");' +
'  var out = document.getElementById("shadowAngleVal");' +
'  if (el && out) out.textContent = el.value + "\u00b0";' +
'  updatePreview();' +
'}' +
// ---- Style Presets: export/import + 3 quick-recall slots -----------
// Scoped to exactly the DOM containers the design covers (Style,
// Colors, Features/\'corners\', Animation) by walking every input/
// select/textarea with an id inside them -- deliberately NOT a hand-
// maintained field list, so this never goes stale as fields get added
// to any of them.
'var PRESET_SCOPE_IDS = ["section-style", "section-colors", "section-corners", "section-animation"];' +
'function collectStyleCornersJson() {' +
'  var obj = {};' +
'  PRESET_SCOPE_IDS.forEach(function (containerId) {' +
'    var container = document.getElementById(containerId);' +
'    if (!container) return;' +
'    var els = container.querySelectorAll("input[id], select[id], textarea[id]");' +
'    els.forEach(function (el) {' +
'      if (el.type === "radio") {' +
'        if (el.checked) obj[el.name] = el.value;' + // one entry per group (its own name, not each option's own id), only for whichever option is actually checked
'        return;' +
'      }' +
'      obj[el.id] = (el.type === "checkbox") ? el.checked : el.value;' +
'    });' +
'  });' +
'  return obj;' +
'}' +
// Sets every id->value pair from a previously-exported (or a preset
// slot\'s saved) object, then re-runs the same cascade of dependent-UI
// handlers each field\'s own onchange would have triggered by hand --
// show/hide rows, slot picker labels, the preview canvas.
'function applyStyleCornersJson(obj) {' +
'  Object.keys(obj).forEach(function (id) {' +
'    var el = document.getElementById(id);' +
'    if (!el) {' +
'      var radio = document.querySelector(\'input[name="\' + id + \'"][value="\' + obj[id] + \'"]\');' + // no plain element has this id -- try it as a radio group name instead
'      if (radio) radio.checked = true;' +
'      return;' +
'    }' +
'    if (el.type === "checkbox") el.checked = !!obj[id]; else el.value = obj[id];' +
'  });' +
'  selectVerticalOption("bgAnimModeGroup", "bgAnimMode", document.getElementById("bgAnimMode").value);' +
'  selectVerticalOption("shakeAnimModeGroup", "shakeAnimMode", document.getElementById("shakeAnimMode").value);' +
'  onBottomStyleChange();' +
'  onMarkerStyleChange();' +
'  updateHandStyleButtonLabel();' +
'  onCornerFontChange();' +
'  onSkyModeChange();' +
'  onShowSecondsChange();' +
'  updateColorRoleButtons();' +
'  updateColorRoleButtons("night");' +
'  renderSlotPicker();' +
'  refreshAllFontTriggerLabels();' +
'  refreshEditButtonLabels();' +
'  updatePreview();' +
'}' +
'function exportDesignJson() {' +
'  document.getElementById("presetExportBox").value = JSON.stringify(collectStyleCornersJson(), null, 2);' +
'}' +
// navigator.clipboard needs a secure context and isn't guaranteed to
// exist in every webview Pebble's settings page might run inside --
// falls back to just selecting the text (same as tapping the box
// itself already does) so the user can still copy it via the
// device's own selection menu.
'function copyExportBoxToClipboard() {' +
'  var box = document.getElementById("presetExportBox");' +
'  var status = document.getElementById("presetExportStatus");' +
'  if (!box.value) exportDesignJson();' +
'  box.select();' +
'  if (navigator.clipboard && navigator.clipboard.writeText) {' +
'    navigator.clipboard.writeText(box.value).then(function () {' +
'      if (status) status.textContent = "Copied to clipboard.";' +
'    }, function () {' +
'      if (status) status.textContent = "Couldn\'t copy automatically -- text is selected, copy it from there.";' +
'    });' +
'  } else if (status) {' +
'    status.textContent = "Couldn\'t copy automatically -- text is selected, copy it from there.";' +
'  }' +
'}' +
'function pasteImportBoxFromClipboard() {' +
'  var box = document.getElementById("presetImportBox");' +
'  var status = document.getElementById("presetImportStatus");' +
'  if (navigator.clipboard && navigator.clipboard.readText) {' +
'    navigator.clipboard.readText().then(function (text) {' +
'      box.value = text;' +
'      if (status) status.textContent = "Pasted -- tap Apply to use it.";' +
'    }, function () {' +
'      if (status) status.textContent = "Couldn\'t read the clipboard automatically -- paste into the box by hand instead.";' +
'    });' +
'  } else if (status) {' +
'    status.textContent = "Clipboard access isn\'t available here -- paste into the box by hand instead.";' +
'  }' +
'}' +
'function importDesignJson() {' +
'  var status = document.getElementById("presetImportStatus");' +
'  var raw = document.getElementById("presetImportBox").value;' +
'  var obj;' +
'  try { obj = JSON.parse(raw); } catch (e) {' +
'    if (status) status.textContent = "Couldn\'t parse that as JSON.";' +
'    return;' +
'  }' +
'  applyStyleCornersJson(obj);' +
'  if (status) status.textContent = "Applied.";' +
'}' +
// Shared "are you sure?" step -- stashes the action to run and shows
// the confirm modal; confirmModalYes() runs it (once) and closes;
// canceling (or tapping outside the box) just closes without running
// anything.
'var s_pendingConfirmAction = null;' +
'function showConfirm(title, message, onConfirm) {' +
'  document.getElementById("confirmModalTitle").textContent = title;' +
'  document.getElementById("confirmModalMessage").textContent = message;' +
'  s_pendingConfirmAction = onConfirm;' +
'  document.getElementById("confirmModal").className = "modal-overlay open";' +
'}' +
'function closeConfirmModal() {' +
'  document.getElementById("confirmModal").className = "modal-overlay";' +
'  s_pendingConfirmAction = null;' +
'}' +
'function confirmModalYes() {' +
'  var action = s_pendingConfirmAction;' +
'  closeConfirmModal();' +
'  if (action) action();' +
'}' +
// One console-style line per logged attempt (newest first), reading
// straight from serviceLogsJson's snapshot of that service's own
// entries -- see servicelog.js's recordAttempt() on the PKJS side for
// exactly what {t, ok, code, label} holds.
'function onShowSecondsChange() {' +
'  var box = document.getElementById("showSeconds");' +
'  var btn = document.getElementById("editSecHandBtn");' +
'  if (btn) btn.disabled = !(box.checked && !box.disabled);' +
'  updatePreview();' +
'}' +
'function onSkyModeChange() {' +
'  updatePreview();' +
'}' +
'function updateWeatherIconStyleTriggerLabel() {' +
'  var sel = document.getElementById("weatherIconStyle");' +
'  var trigger = document.getElementById("weatherIconStyleTrigger");' +
'  if (!sel || !trigger) return;' +
'  var preview = trigger.querySelector(".weather-icon-style-preview");' +
'  var name = trigger.querySelector(".font-picker-name");' +
'  var src = WEATHER_ICON_STYLE_PREVIEWS[sel.value];' +
'  if (preview) preview.innerHTML = src ? \'<img src="\' + src + \'" alt="">\' : "";' +
'  if (name) name.textContent = WEATHER_ICON_STYLE_NAMES[parseInt(sel.value, 10)] || "";' +
'}' +
'function openWeatherIconStylePicker() {' +
'  renderWeatherIconStylePickerGrid();' +
'  document.getElementById("weatherIconStylePickerModal").className = "modal-overlay open";' +
'}' +
'function closeWeatherIconStylePicker() {' +
'  document.getElementById("weatherIconStylePickerModal").className = "modal-overlay";' +
'}' +
'function renderWeatherIconStylePickerGrid() {' +
'  var sel = document.getElementById("weatherIconStyle");' +
'  var currentVal = sel ? sel.value : "1";' +
'  var html = "";' +
'  for (var i = 0; i < WEATHER_ICON_STYLE_NAMES.length; i++) {' +
'    var src = WEATHER_ICON_STYLE_PREVIEWS[String(i)];' +
'    var selected = String(i) === String(currentVal);' +
'    html += \'<button type="button" class="font-picker-btn\' + (selected ? " selected" : "") + \'" onclick="chooseWeatherIconStyle(\' + i + \')">\' +' +
'      \'<span class="font-picker-preview weather-icon-style-preview">\' + (src ? \'<img src="\' + src + \'" alt="">\' : "") + "</span>" +' +
'      \'<span class="font-picker-name">\' + esc(WEATHER_ICON_STYLE_NAMES[i]) + "</span></button>";' +
'  }' +
'  document.getElementById("weatherIconStylePickerGrid").innerHTML = html;' +
'}' +
'function chooseWeatherIconStyle(value) {' +
'  var sel = document.getElementById("weatherIconStyle");' +
'  if (sel) sel.value = value;' +
'  closeWeatherIconStylePicker();' +
'  updateWeatherIconStyleTriggerLabel();' +
'}' +
// Shows/hides the Hollow thickness slider based on the Hollow
// checkbox -- called both on the checkbox's own onchange and once up
// front when the popup opens/gets prefilled.
'function selectBottomStyle(val) {' +
'  document.getElementById("bottomStyleValue").value = val;' +
'  var buttons = document.getElementById("bottomStyleGroup").getElementsByClassName("mode-btn");' +
'  var order = ["digital", "analog"];' +
'  for (var i = 0; i < buttons.length; i++) {' +
'    buttons[i].className = "mode-btn" + (order[i] === val ? " active" : "");' +
'  }' +
'  onBottomStyleChange();' +
'}' +
// Falls back to the group's first button (Off, for every current
// caller) when val doesn't match any button's own data-value -- same
// reasoning as verticalButtonGroupHtml()'s own comment, but for
// values arriving after the initial render (a preset being applied
// via applyStyleCornersJson(), which sets the hidden field\'s value
// straight from possibly-stale saved JSON before calling this). Also
// corrects the hidden field itself to the fallback value, not just
// the highlighted button, so a subsequent Save persists the sane
// fallback rather than the original invalid string.
'function selectVerticalOption(groupId, hiddenId, val) {' +
'  var buttons = document.getElementById(groupId).getElementsByClassName("mode-btn-vertical");' +
'  var matched = false;' +
'  for (var i = 0; i < buttons.length; i++) {' +
'    if (buttons[i].getAttribute("data-value") === val) { matched = true; break; }' +
'  }' +
'  if (!matched && buttons.length) val = buttons[0].getAttribute("data-value");' +
'  document.getElementById(hiddenId).value = val;' +
'  for (var j = 0; j < buttons.length; j++) {' +
'    buttons[j].className = "mode-btn-vertical" + (buttons[j].getAttribute("data-value") === val ? " active" : "");' +
'  }' +
'  updatePreview();' +
'}' +
// Same "hidden field is the real value, buttons just reflect it"
// mechanics as selectVerticalOption() above, for a modeButtonGroupHtml()
// row instead of a verticalButtonGroupHtml() one -- shared by every
// converted dropdown below except Sky style, which needs its own
// extra step (see selectSkyMode() right after this).
'function selectModeButton(groupId, hiddenId, val) {' +
'  document.getElementById(hiddenId).value = val;' +
'  var buttons = document.getElementById(groupId).getElementsByClassName("mode-btn");' +
'  for (var i = 0; i < buttons.length; i++) {' +
'    buttons[i].className = "mode-btn" + (buttons[i].getAttribute("data-value") === val ? " active" : "");' +
'  }' +
'}' +
// For the few places something OTHER than a direct button tap changes
// one of these hidden fields\' value -- a preset being applied, or a
// popup being pre-filled from already-saved state on open -- and the
// button group needs to catch up to reflect it, since setting
// .value on the hidden input alone (the way any of those already did
// before the field in question was a plain <select>) doesn\'t touch
// the buttons\' own "active" class the way a real tap does via
// selectModeButton() above.
'function refreshModeButtonGroup(groupId, hiddenId) {' +
'  var group = document.getElementById(groupId);' +
'  var hidden = document.getElementById(hiddenId);' +
'  if (!group || !hidden) return;' +
'  var buttons = group.getElementsByClassName("mode-btn");' +
'  for (var i = 0; i < buttons.length; i++) {' +
'    buttons[i].className = "mode-btn" + (buttons[i].getAttribute("data-value") === hidden.value ? " active" : "");' +
'  }' +
'}' +
'function selectSkyMode(val) {' +
'  selectModeButton("skyModeGroup", "skyMode", val);' +
'  onSkyModeChange();' +
'}' +
'function onOutlineStyleChange(val) {' +
'  selectModeButton("outlineStyleGroup", "outlineStyle", val);' +
'  updatePreview();' +
'}' +
'function selectShadowTranslucent(val) {' +
'  selectModeButton("shadowTranslucentGroup", "shadowTranslucent", val);' +
'  refreshEditButtonLabels();' +
'  updatePreview();' +
'}' +
'function onAnalogStyleChange() { updatePreview(); }' +

'function hexToByte(hex) {' +
'  var r = parseInt(hex.substr(1, 2), 16), g = parseInt(hex.substr(3, 2), 16), b = parseInt(hex.substr(5, 2), 16);' +
'  function to2bit(v) { return Math.round(v / 85); }' +
'  return packedByteFor(to2bit(r), to2bit(g), to2bit(b));' +
'}' +

// ---- Color preset picker -------------------------------------------
// A preset\'s own `label` is already written as "<Main> on <Background>"
// (optionally followed by ", <Accent> accent" when the accent differs
// from the main color -- see COLOR_SCHEMES\' own comment) -- these two
// helpers split that one string back into the two separate pieces this
// popup shows on its own two lines, rather than duplicating the accent
// name a second time by showing the label\'s full text verbatim on line
// 1 as well as again on line 2.
'function goBack() {' +
'  document.location = getQueryParam("return_to", "pebblejs://close#");' +
'}' +
'function openDonateModal() {' +
'  document.getElementById("donateModal").className = "modal-overlay open";' +
'}' +
'function closeDonateModal() {' +
'  document.getElementById("donateModal").className = "modal-overlay";' +
'}' +
// The bar's own height varies by device (font scaling, safe-area
// insets) and is capped at 25vh by CSS, so this measures it after
// layout rather than assuming a fixed value, and pushes the
// scrollable content down by exactly that much so nothing starts out
// hidden underneath it.
'function adjustTopBarSpacing() {' +
'  var bar = document.getElementById("topBar");' +
'  if (!bar) return;' +
'  document.body.style.paddingTop = bar.offsetHeight + "px";' +
'}' +
'window.addEventListener("load", adjustTopBarSpacing);' +
'window.addEventListener("resize", adjustTopBarSpacing);' +
'function customHiddenIdFor(role, scheme) {' +
'  var prefix = scheme === "night" ? "night" : "";' +
'  if (role === "text") return prefix ? "nightCustomTextValue" : "customTextValue";' +
'  if (role === "accent") return prefix ? "nightCustomAccentValue" : "customAccentValue";' +
'  return prefix ? "nightCustomBgValue" : "customBgValue";' +
'}' +

// Converts 0-255 RGB to HSL (h in degrees 0-360, s/l 0-1) -- used to
// arrange the wheel by hue, the way a real color wheel reads.
// Exact layout of Pebble's real color-picker tool (developer.rebble.io/
// guides/tools-and-resources/color-picker/), extracted directly from
// its SVG: each hexagon's pixel center was converted to axial (q, r)
// hex-grid coordinates (pointy-top orientation -- flat left/right
// sides, pointed top/bottom vertices, unlike the flat-top approximation
// used before), and matched to its packed color byte. The shape isn't
// a simple symmetric hexagon; flood-filling from outside the shape\'s
// bounding box found exactly 5 cells fully enclosed by colored
// neighbors on all sides but not themselves colored -- those are the
// genuine hollow gaps, listed separately below.
'var PEBBLE_WHEEL_POSITIONS = [' +
'{q:-5,r:2,b:239},{q:-4,r:1,b:223},{q:-3,r:-1,b:222},{q:-3,r:0,b:206},{q:-3,r:1,b:207},{q:-3,r:3,b:219},{q:-3,r:4,b:199},{q:-2,r:-4,b:238},{q:-2,r:-3,b:221},{q:-2,r:-2,b:205},{q:-2,r:-1,b:201},{q:-2,r:0,b:202},{q:-2,r:2,b:203},{q:-2,r:3,b:195},{q:-2,r:4,b:215},{q:-2,r:5,b:235},{q:-1,r:-3,b:204},{q:-1,r:-2,b:200},{q:-1,r:-1,b:217},{q:-1,r:0,b:218},{q:-1,r:1,b:198},{q:-1,r:2,b:194},{q:-1,r:3,b:211},{q:-1,r:4,b:214},{q:0,r:-4,b:220},{q:0,r:-2,b:216},{q:0,r:-1,b:196},{q:0,r:0,b:197},{q:0,r:2,b:193},{q:0,r:3,b:210},{q:0,r:4,b:227},{q:0,r:5,b:231},{q:1,r:-5,b:237},{q:1,r:-4,b:236},{q:1,r:-2,b:233},{q:1,r:-1,b:212},{q:1,r:2,b:209},{q:1,r:3,b:226},{q:1,r:4,b:230},{q:2,r:-2,b:232},{q:2,r:1,b:208},{q:2,r:2,b:225},{q:2,r:3,b:243},{q:2,r:4,b:247},{q:3,r:-3,b:252},{q:3,r:-2,b:248},{q:3,r:-1,b:228},{q:3,r:0,b:229},{q:3,r:1,b:224},{q:3,r:2,b:242},{q:3,r:3,b:246},{q:3,r:4,b:251},{q:4,r:-5,b:254},{q:4,r:-4,b:253},{q:4,r:-3,b:249},{q:4,r:-2,b:244},{q:4,r:-1,b:240},{q:4,r:0,b:241},{q:5,r:-1,b:245},{q:6,r:-5,b:234},{q:6,r:-4,b:192},{q:6,r:-2,b:250},{q:7,r:-5,b:255},{q:7,r:-4,b:213}' +
'];' +
'var PEBBLE_WHEEL_HOLLOW = [{q:0,r:1},{q:1,r:0},{q:1,r:1},{q:2,r:-1},{q:2,r:0}];' +

'function getQueryParam(name, defaultValue) {' +
'  var query = location.search.substring(1);' +
'  var vars = query.split("&");' +
'  for (var i = 0; i < vars.length; i++) {' +
'    var pair = vars[i].split("=");' +
'    if (pair[0] === name) return decodeURIComponent(pair[1] || "");' +
'  }' +
'  return defaultValue;' +
'}' +

// ---- section sub-headers -------------------------------------------
// One compute*Subheader() function per collapsible section, each
// returning the one-line summary text (or, for Colors, an HTML
// fragment with its own 3 color dots) shown under that section's
// title while it's collapsed -- see sectionLegendHtml() near the top
// of this file for the markup itself and toggleSection() above for
// why it disappears on expansion. setSubheaderText()/Html() below
// just push a function's return value into that section's own
// #subhead-<id> span; refreshAllSectionSubheaders() calls the whole
// set together. None of these mutate anything -- purely read the same
// DOM fields every other part of this page already treats as the
// source of truth (hidden inputs, checkboxes, selects), so a
// sub-header can never show something Save wouldn\'t actually send.
'function setSubheaderText(id, text) {' +
'  var el = document.getElementById("subhead-" + id);' +
'  if (el) el.textContent = text;' +
'}' +
'function setSubheaderHtml(id, html) {' +
'  var el = document.getElementById("subhead-" + id);' +
'  if (el) el.innerHTML = html;' +
'}' +
'function computeStyleSubheader() {' +
'  var bottomStyleVal = document.getElementById("bottomStyleValue").value;' +
'  var clockPart;' +
'  if (bottomStyleVal === "analog") {' +
'    clockPart = "analog clock";' +
'  } else {' +
'    var fontId = parseInt(document.getElementById("clockFont").value, 10);' +
'    clockPart = fontLookupEntry(fontId).label + " digital clock";' +
'  }' +
'  var skyVal = document.getElementById("skyMode").value || "0";' +
'  var skyPart = skyVal === "1" ? "clear sky" : skyVal === "2" ? "space sky" : "weather sky";' +
'  var outlineVal = document.getElementById("outlineStyle").value || "1";' +
'  var outlinePart = outlineVal === "0" ? "no outline" : outlineVal === "2" ? "thick outline" : "thin outline";' +
'  return clockPart + " + " + skyPart + " + " + outlinePart;' +
'}' +
// The only sub-header rendered as HTML rather than plain text -- the
// 3 small color dots (see .subhead-dot) need real background-color
// styling, not just words. dayColors()/nightColors()/isNightNowApprox()
// are all existing helpers this page already uses for the color-role
// swatches and the "Active now" badge above.
'function computeAnimationSubheader() {' +
'  var parts = [];' +
'  var startup = document.getElementById("startupClockAnimMode").value;' +
'  if (startup === "2") parts.push("planet sweep time shift on start");' +
'  else if (startup === "1") parts.push("animated clock on start");' +
'  var bg = document.getElementById("bgAnimMode").value;' +
'  if (bg === "1") parts.push("planets on start");' +
'  else if (bg === "2") parts.push("indices on start");' +
'  var shake = document.getElementById("shakeAnimMode").value;' +
'  var shakeParts = [];' +
'  if (shake === "2" || shake === "3") shakeParts.push("planets");' +
'  if (shake === "1" || shake === "3") shakeParts.push("second hand");' +
'  if (shakeParts.length) parts.push(shakeParts.join(" and ") + " on shake");' +
'  if (!parts.length) return "No animations active";' +
'  var s = parts.join(", ");' +
'  return s.charAt(0).toUpperCase() + s.slice(1);' +
'}' +
'function computeWeatherSubheader() {' +
'  var tempUnit = document.getElementById("tempUnit").value;' +
'  var tempLabel = tempUnit === "F" ? "Fahrenheit" : tempUnit === "K" ? "Kelvin" : "Celsius";' +
'  var wind = document.getElementById("windSpeedUnit").value;' +
'  var windLabel = wind === "mph" ? "imperial" : wind === "kn" ? "nautical" : "metric";' +
'  var aqi = document.getElementById("aqiUnit").value;' +
'  var aqiLabel = aqi === "1" ? "European" : "US";' +
'  return tempLabel + " temp. units with " + windLabel + " and " + aqiLabel + " air quality";' +
'}' +
'function computeAstronomySubheader() {' +
'  var sizeVal = document.getElementById("sunMoonSize").value;' +
'  var sizeLabel = sizeVal === "100" ? "Large" : sizeVal === "50" ? "Small" : sizeVal === "25" ? "X-small" : "Medium";' +
'  var parts = [sizeLabel + " sun&moon"];' +
'  parts.push("ISS " + (document.getElementById("showIss").checked ? "on" : "off"));' +
'  parts.push("auroras " + (document.getElementById("auroraEnabled").checked ? "on" : "off"));' +
'  if (document.getElementById("vibrateOnPhaseChange").checked) parts.push("vibrate on eclipse phases");' +
'  return parts.join(", ");' +
'}' +
'function computeLocationSubheader() {' +
'  if (document.getElementById("autoLoc").checked) return "Use phone location";' +
'  var nameEl = document.getElementById("locationName");' +
'  var name = nameEl ? nameEl.value : "";' +
'  if (name) return "Use " + name;' +
'  var lat = document.getElementById("lat").value;' +
'  var lon = document.getElementById("lon").value;' +
'  if (!lat && !lon) return "Use phone location";' +
'  return "Use lat: " + lat + ", long: " + lon;' +
'}' +
'function computeUpdatesSubheader() {' +
'  var mins = document.getElementById("updateMins").value;' +
'  var saver = document.getElementById("batterySaverEnabled").checked;' +
'  return mins + " minute interval, battery preserver " + (saver ? "on" : "off");' +
'}' +
'function formatTestDateTime(val) {' +
'  if (!val) return null;' +
'  var parts = val.split("T");' +
'  if (parts.length < 2) return val;' +
'  var dateParts = parts[0].split("-");' +
'  if (dateParts.length !== 3) return val;' +
'  var months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];' +
'  var y = dateParts[0], m = parseInt(dateParts[1], 10) - 1, d = parseInt(dateParts[2], 10);' +
'  return d + " " + (months[m] || "") + " " + y + " " + parts[1];' +
'}' +
'function refreshAllSectionSubheaders() {' +
'  try { setSubheaderText("examples", EXAMPLE_STYLE_COUNT + " styles available"); } catch (e) {}' +
'  try { setSubheaderText("style", computeStyleSubheader()); } catch (e) {}' +
'  try { setSubheaderHtml("colors", computeColorsSubheaderHtml()); } catch (e) {}' +
'  try { setSubheaderText("corners", computeFeaturesSubheader()); } catch (e) {}' +
'  try { setSubheaderText("animation", computeAnimationSubheader()); } catch (e) {}' +
'  try { setSubheaderText("presets", computePresetsSubheader()); } catch (e) {}' +
'  try { setSubheaderText("weather", computeWeatherSubheader()); } catch (e) {}' +
'  try { setSubheaderText("astronomy", computeAstronomySubheader()); } catch (e) {}' +
'  try { setSubheaderText("location", computeLocationSubheader()); } catch (e) {}' +
'  try { setSubheaderText("updates", computeUpdatesSubheader()); } catch (e) {}' +
'  try { setSubheaderText("testing", computeDebugSubheader()); } catch (e) {}' +
'}' +
// A single delegated hook per event type instead of threading
// refreshAllSectionSubheaders() into every existing onclick/onchange/
// oninput handler on the page (mode-btn taps, slider drags, modal
// confirms, preset apply, example-style apply, etc. -- there are
// dozens). Bubbling means each of these fires AFTER whatever inline
// handler the actual target element already has, so the DOM is
// already up to date by the time this runs.
'document.addEventListener("click", refreshAllSectionSubheaders);' +
'document.addEventListener("change", refreshAllSectionSubheaders);' +
'document.addEventListener("input", refreshAllSectionSubheaders);' +

'updateColorRoleButtons("day");' +
'updateColorRoleButtons("night");' +
'onBottomStyleChange();' +
'onMarkerStyleChange();' +
'updateHandStyleButtonLabel();' +
'refreshAllFontTriggerLabels();' +
'refreshEditButtonLabels();' +
'renderHandStyleGrid();' +
'renderMarkerStyleGrid();' +
'renderCategoryButtons();' +
'updateWeatherIconStyleVisibility();' +
'adjustTopBarSpacing();' +
'if (document.fonts && document.fonts.ready) { document.fonts.ready.then(updatePreview); }' +
'updateSchemeActiveHighlight();' +
'refreshAllSectionSubheaders();' +
// One-shot only -- if manual location is already on and coordinates
// are present but nothing's cached yet (e.g. an existing install
// updating into this feature for the first time, or lat/lon set some
// other way than the Search box/blur handler above), resolve a name
// once now rather than leaving the Location sub-header stuck showing
// raw coordinates forever.
'if (!document.getElementById("autoLoc").checked && document.getElementById("lat").value && document.getElementById("lon").value && !document.getElementById("locationName").value) {' +
'  reverseGeocodeAndCacheLocationName();' +
'}' +
'setInterval(function () { updatePreview(); updateSchemeActiveHighlight(); refreshAllSectionSubheaders(); }, 1000);' +
''
  );
};
