'use strict';

// Runtime fragment extracted from config-page.js.
// The fragment is still generated by PKJS and executed inside the settings page.
module.exports = function buildRuntimeFragment() {
  return (
'function loadRawMessage(i) {' +
'  var all = [];' +
'  try { all = JSON.parse(document.getElementById("rawMessageLogJson").value || "[]"); } catch (e) {}' +
'  var entry = all[i];' +
'  if (!entry) return;' +
'  document.getElementById("debugData").value = JSON.stringify(entry.dict, null, 2);' +
'  var grid = document.getElementById("rawLogBtnGrid");' +
'  if (grid) {' +
'    var btns = grid.getElementsByClassName("raw-log-btn");' +
'    for (var j = 0; j < btns.length; j++) btns[j].className = "raw-log-btn";' +
'  }' +
'  var btn = document.getElementById("rawLogBtn" + i);' +
'  if (btn) btn.className = "raw-log-btn active";' +
'}' +
'function copyTextareaContent(textareaId, btnId) {' +
'  var ta = document.getElementById(textareaId);' +
'  ta.focus();' +
'  ta.select();' +
'  ta.setSelectionRange(0, 999999);' +
'  var ok = false;' +
'  try { ok = document.execCommand("copy"); } catch (e) {}' +
'  var btn = document.getElementById(btnId);' +
'  if (btn) {' +
'    var original = btn.textContent;' +
'    btn.textContent = ok ? "Copied!" : "Copy failed";' +
'    setTimeout(function () { btn.textContent = original; }, 1500);' +
'  }' +
'}' +
// The "Send full keyset to watch now" button below -- reads whatever
// is CURRENTLY in the fullKeysetData textarea (the auto-generated
// snapshot from page load, or whatever the person edited it to since
// then), closes the settings page carrying it plus a marker flag, and
// returns. index.js's webviewclosed handler checks for that flag
// before anything else and, if set, parses this text and sends it
// chunked to the watch AS-IS -- skipping every normal setSetting()/
// sendFlatDict()/refreshAndSend() call entirely, so nothing else
// changes and nothing here gets persisted. A deliberately different,
// parallel exit from the page than the normal Save button\'s -- Save
// itself never sets this flag, so an ordinary save is completely
// unaffected by this textarea\'s contents.
'function sendFullKeysetToWatch() {' +
'  var text = document.getElementById("fullKeysetData").value;' +
'  try {' +
'    JSON.parse(text);' +
'  } catch (e) {' +
'    alert("Not valid JSON -- fix the text before sending:\\n\\n" + e.message);' +
'    return;' +
'  }' +
'  var returnTo = getQueryParam("return_to", "pebblejs://close#");' +
'  var payload = { CONFIG_SEND_FULL_KEYSET: true, CONFIG_FULL_KEYSET_DATA: text };' +
'  document.location = returnTo + encodeURIComponent(JSON.stringify(payload));' +
'}' +
// Boils a Nominatim `address` object (city/town/village/... + country)
// down to the short "City, Country" form the Location sub-header shows
// (see computeLocationSubheader() below) -- falls back gracefully to
// whichever half is actually present rather than requiring both.
'function openServiceLog(service, label) {' +
'  var all = {};' +
'  try { all = JSON.parse(document.getElementById("serviceLogsJson").value || "{}"); } catch (e) {}' +
'  document.getElementById("serviceLogModalTitle").textContent = label + " \\u2014 last attempts";' +
'  var entries = (all[service] && all[service].log) || [];' +
'  var body = document.getElementById("serviceLogModalBody");' +
'  body.innerHTML = "";' +
'  if (entries.length === 0) {' +
'    var empty = document.createElement("div");' +
'    empty.className = "help";' +
'    empty.textContent = "No attempts logged yet.";' +
'    body.appendChild(empty);' +
'  } else {' +
'    entries.slice().reverse().forEach(function (e) {' +
'      var d = new Date(e.t);' +
'      var line = document.createElement("div");' +
'      line.className = "service-log-line";' +
'      var status = e.ok ? "OK" : ("ERR " + e.code + " - " + e.label);' +
'      line.textContent = d.toLocaleDateString() + " " + d.toLocaleTimeString() + "  " + label + "  " + status;' +
'      body.appendChild(line);' +
'    });' +
'  }' +
'  document.getElementById("serviceLogModal").className = "modal-overlay open";' +
'}' +
'function closeServiceLogModal() {' +
'  document.getElementById("serviceLogModal").className = "modal-overlay";' +
'}' +
'function computeDebugSubheader() {' +
'  var testOn = document.getElementById("testMode").checked;' +
'  var overridePart = testOn ? ("Override: " + (formatTestDateTime(document.getElementById("testDateTime").value) || "not set")) : "Override: off";' +
'  var lastPart = "last: none yet";' +
'  try {' +
'    var log = JSON.parse(document.getElementById("rawMessageLogJson").value || "[]");' +
'    if (log.length) {' +
'      var last = log[log.length - 1];' +
'      var d = new Date(last.t);' +
'      function pad(n, len) { var s = String(n); while (s.length < (len || 2)) s = "0" + s; return s; }' +
'      lastPart = "last " + pad(d.getHours()) + ":" + pad(d.getMinutes()) + ":" + pad(d.getSeconds()) + "." + pad(d.getMilliseconds(), 3);' +
'    }' +
'  } catch (e) {}' +
'  return overridePart + ", " + lastPart;' +
'}' + ''
// Called on init, after every click/change/input anywhere on the page
// (see the delegated listeners below -- cheaper and far less fragile
// than hunting down every individual onclick/onchange handler that
// could affect one of these), and once a second alongside the
// existing preview/scheme-highlight timer (for the Colors day/night
// split and the Debug section\'s own last-message clock, both of which
// can go stale purely from time passing, not from any click).
// Each section wrapped in its own try/catch so one section\'s bug
// (or a not-yet-rendered field, e.g. during the very first call before
// every element exists) can\'t blank out every other section\'s
// sub-header.
  );
};
