'use strict';

// Runtime fragment extracted from config-page.js.
// The fragment is still generated by PKJS and executed inside the settings page.
module.exports = function buildRuntimeFragment() {
  return (
'function slotAvailable(wrapId) {' +
'  var avail = computeSlotAvailability();' +
'  switch (wrapId) {' +
'    case "cornerTLWrap": case "cornerTRWrap": case "cornerBLWrap": case "cornerBRWrap":' +
'      return !avail.cornersGrayed;' +
'    case "upperMiddleWrap": return avail.upper;' +
'    case "bottomMiddleWrap": return avail.bottom;' +
'    case "middleLeftWrap": return avail.left;' +
'    case "middleRightWrap": return avail.right;' +
'    default: return false;' +
'  }' +
'}' +

'function drawCornerSlot(ctx, contentId, colorId, x, y, textAlign, colors) {' +
'  var contentEl = document.getElementById(contentId);' +
'  var colorEl = document.getElementById(colorId);' +
'  if (!contentEl || !colorEl) return;' +
'  var content = parseInt(contentEl.value, 10);' +
'  var label = CORNER_PREVIEW_LABELS[content];' +
'  if (!label) return;' +
'  var mode = parseInt(colorEl.value, 10);' +
'  var color = colors.text, alpha = 1;' +
'  if (mode === 1) { color = colors.accent; }' +
'  else if (mode === 2) { color = colors.accent; alpha = 0.55; }' +
'  else if (mode === 3) { color = "#4caf50"; }' +
'  ctx.font = "bold 9px sans-serif";' +
'  ctx.textAlign = textAlign;' +
'  ctx.textBaseline = "top";' +
'  ctx.globalAlpha = alpha;' +
'  ctx.fillStyle = color;' +
'  ctx.fillText(label, x, y);' +
'  ctx.globalAlpha = 1;' +
'}' +

// Direct port of features_recompute_layout()'s own margin computation
// (background_layer.c/features_layer.c) -- how far in from each edge
// the "middle" feature slots (upper/bottom-middle, middle-left/right)
// have to start so they land INSIDE the empty area the current marker
// style/hands actually leave clear, rather than overlapping the
// marker ring. 44/40/30/30 are the same defaults (and BITMAP_STYLE_
// MARGINS\' own values, identical across all 5 bitmap styles) the
// watch falls back to; for the procedural presets (0-2) and custom (8)
// the margin instead grows to wherever that style\'s own inner ring
// boundary reaches at each of the 4 cardinal points, via the exact
// same point_on_ring() technique the marker ring itself is drawn with.
// Values returned are already scaled into this canvas\'s own pixel
// space (see readHandConfig()\'s own `scale` comment for why that\'s
// needed at all).
'function computeMiddleFeatureMargins(w, h) {' +
'  var scale = w / 200;' +
'  var margins = { top: 44 * scale, bottom: 40 * scale, left: 30 * scale, right: 30 * scale };' +
'  var markerStyle = parseInt(document.getElementById("bigAnalogMarkerStyle").value, 10);' +
'  var isBitmapStyle = markerStyle >= 3 && markerStyle !== 8 && markerStyle !== 9;' +
'  if (isBitmapStyle) return margins;' + // BITMAP_STYLE_MARGINS's 5 entries are all identical to the defaults above -- nothing to differ
'  var pct, ecc;' +
'  if (markerStyle === 8) {' +
'    var hourCfg = readCustomMarkerConfig("hour");' +
'    pct = hourCfg.innerBorderPct; ecc = hourCfg.innerEccentricity;' +
'  } else if (markerStyle <= 2) {' +
'    var hour = MARKER_STYLE_HOUR_PRESETS[markerStyle], sec = MARKER_STYLE_SECOND_PRESETS[markerStyle];' +
'    if (sec.thickness === 0 || hour.innerBorderPct <= sec.innerBorderPct) { pct = hour.innerBorderPct; ecc = hour.innerEccentricity; }' +
'    else { pct = sec.innerBorderPct; ecc = sec.innerEccentricity; }' +
'  } else { pct = 100; ecc = 0; }' + // 9 ("none") or anything unrecognized -- background_marker_inner_reach()'s own "fully retracted" fallback
'  var cx = w / 2, cy = h / 2;' +
'  var topPt = pointOnRing(cx, cy, w, h, 0, pct, ecc);' +
'  var rightPt = pointOnRing(cx, cy, w, h, Math.PI / 2, pct, ecc);' +
'  var bottomPt = pointOnRing(cx, cy, w, h, Math.PI, pct, ecc);' +
'  var leftPt = pointOnRing(cx, cy, w, h, 3 * Math.PI / 2, pct, ecc);' +
'  var margin = 4 * scale;' +
'  if (topPt.y + margin > margins.top) margins.top = topPt.y + margin;' +
'  if (h - bottomPt.y + margin > margins.bottom) margins.bottom = h - bottomPt.y + margin;' +
'  var leftReach = leftPt.x + margin, rightReach = w - rightPt.x + margin;' +
'  if (leftReach > margins.left) margins.left = leftReach;' +
'  if (rightReach > margins.right) margins.right = rightReach;' +
'  return margins;' +
'}' +

'function categoryForContentId(contentId) {' +
'  var idNum = parseInt(contentId, 10);' +
'  for (var i = 0; i < CORNER_CATEGORIES.length; i++) {' +
'    for (var j = 0; j < CORNER_CATEGORIES[i].items.length; j++) {' +
'      if (CORNER_CATEGORIES[i].items[j].id === idNum) return CORNER_CATEGORIES[i].id;' +
'    }' +
'  }' +
'  return "none";' + // unrecognized id -- fall back rather than leave both dropdowns unset
'}' +
'function findCategory(categoryId) {' +
'  for (var i = 0; i < CORNER_CATEGORIES.length; i++) {' +
'    if (CORNER_CATEGORIES[i].id === categoryId) return CORNER_CATEGORIES[i];' +
'  }' +
'  return CORNER_CATEGORIES[0];' +
'}' +
'function categoryItemOptionsHtml(categoryId, selectedContentId) {' +
'  var items = findCategory(categoryId).items;' +
'  var html = "";' +
'  for (var i = 0; i < items.length; i++) {' +
'    html += "<option value=\\"" + items[i].id + "\\"" + (String(selectedContentId) === String(items[i].id) ? " selected" : "") + ">" + items[i].label + "</option>";' +
'  }' +
'  return html;' +
'}' +
'var SLOT_DEFS = {' +
'  cornerTL: { contentId: "cornerTL", colorId: "cornerTLColor", btnId: "slotBtn-cornerTL", label: "Top-left", avail: function (a) { return !a.cornersGrayed; } },' +
'  cornerTR: { contentId: "cornerTR", colorId: "cornerTRColor", btnId: "slotBtn-cornerTR", label: "Top-right", avail: function (a) { return !a.cornersGrayed; } },' +
'  cornerBL: { contentId: "cornerBL", colorId: "cornerBLColor", btnId: "slotBtn-cornerBL", label: "Bottom-left", avail: function (a) { return !a.cornersGrayed; } },' +
'  cornerBR: { contentId: "cornerBR", colorId: "cornerBRColor", btnId: "slotBtn-cornerBR", label: "Bottom-right", avail: function (a) { return !a.cornersGrayed; } },' +
'  upperMiddleLine1: { contentId: "upperMiddleLine1Content", colorId: "upperMiddleLine1Color", btnId: "slotBtn-upperMiddleLine1", label: "Upper-middle, line 1", analogOnly: true, avail: function (a) { return a.upper; } },' +
'  upperMiddleLine2: { contentId: "upperMiddleLine2Content", colorId: "upperMiddleLine2Color", btnId: "slotBtn-upperMiddleLine2", label: "Upper-middle, line 2", analogOnly: true, avail: function (a) { return a.upper; } },' +
'  bottomMiddleLine1: { contentId: "bottomMiddleLine1Content", colorId: "bottomMiddleLine1Color", btnId: "slotBtn-bottomMiddleLine1", label: "Bottom-middle, line 1", analogOnly: true, avail: function (a) { return a.bottom; } },' +
'  bottomMiddleLine2: { contentId: "bottomMiddleLine2Content", colorId: "bottomMiddleLine2Color", btnId: "slotBtn-bottomMiddleLine2", label: "Bottom-middle, line 2", analogOnly: true, avail: function (a) { return a.bottom; } },' +
'  middleLeftLine1: { contentId: "middleLeftLine1Content", colorId: "middleLeftLine1Color", btnId: "slotBtn-middleLeftLine1", label: "Middle-left, line 1", analogOnly: true, avail: function (a) { return a.left; } },' +
'  middleLeftLine2: { contentId: "middleLeftLine2Content", colorId: "middleLeftLine2Color", btnId: "slotBtn-middleLeftLine2", label: "Middle-left, line 2", analogOnly: true, avail: function (a) { return a.left; } },' +
'  middleRightLine1: { contentId: "middleRightLine1Content", colorId: "middleRightLine1Color", btnId: "slotBtn-middleRightLine1", label: "Middle-right, line 1", analogOnly: true, avail: function (a) { return a.right; } },' +
'  middleRightLine2: { contentId: "middleRightLine2Content", colorId: "middleRightLine2Color", btnId: "slotBtn-middleRightLine2", label: "Middle-right, line 2", analogOnly: true, avail: function (a) { return a.right; } },' +
  // digitalLeft/Right/Bottom below deliberately point contentId/colorId
  // at the SAME underlying elements as their analog counterparts
  // (middleLeftLine1/2, middleRightLine1/2, upperMiddleLine1/2,
  // bottomMiddleLine1) rather than a separate set of digital-only ones
  // -- matches eclipse_data.h's own dual-purpose field reuse, and since
  // analogOnly/digitalOnly slots are never both visible at once (see
  // renderSlotPicker()), two SLOT_DEFS entries safely sharing one
  // underlying <select>/<input> pair is no different from any other
  // slot reading/writing its own.
'  digitalLeft1: { contentId: "middleLeftLine1Content", colorId: "middleLeftLine1Color", btnId: "slotBtn-digitalLeft1", label: "Left side, row 1 (top)", digitalOnly: true, avail: function (a) { return a.digitalLeft; } },' +
'  digitalLeft2: { contentId: "middleLeftLine2Content", colorId: "middleLeftLine2Color", btnId: "slotBtn-digitalLeft2", label: "Left side, row 2", digitalOnly: true, avail: function (a) { return a.digitalLeft; } },' +
'  digitalLeft3: { contentId: "upperMiddleLine1Content", colorId: "upperMiddleLine1Color", btnId: "slotBtn-digitalLeft3", label: "Left side, row 3 (bottom)", digitalOnly: true, avail: function (a) { return a.digitalLeft; } },' +
'  digitalRight1: { contentId: "middleRightLine1Content", colorId: "middleRightLine1Color", btnId: "slotBtn-digitalRight1", label: "Right side, row 1 (top)", digitalOnly: true, avail: function (a) { return a.digitalRight; } },' +
'  digitalRight2: { contentId: "middleRightLine2Content", colorId: "middleRightLine2Color", btnId: "slotBtn-digitalRight2", label: "Right side, row 2", digitalOnly: true, avail: function (a) { return a.digitalRight; } },' +
'  digitalRight3: { contentId: "upperMiddleLine2Content", colorId: "upperMiddleLine2Color", btnId: "slotBtn-digitalRight3", label: "Right side, row 3 (bottom)", digitalOnly: true, avail: function (a) { return a.digitalRight; } },' +
'  digitalBottom: { contentId: "bottomMiddleLine1Content", colorId: "bottomMiddleLine1Color", btnId: "slotBtn-digitalBottom", label: "Bottom feature", digitalOnly: true, avail: function () { return true; } }' +
'};' +
'var CURRENT_SLOT_KEY = null;' +
'var SLOT_EDITOR_DRAFT_COLOR = 0;' +
// Procedural marker styles (<3) have all 8 slots and the 4 corners;
// bitmap styles are each limited to whatever their own artwork
// actually has room for and (Tally excepted -- its own mask leaves
// all 4 corners clear) suppress the corners -- and, for the styles
// whose mask only really has room for upper+bottom, the left/right
// edges too -- by default, since the mask fills most of the rest of
// the screen either way. The "Incompatible features" checkbox
// (bitmapCornerOverride) unlocks all of it at once: corners AND
// whichever middle edges that style would otherwise leave off, not
// just the corners.
'function computeSlotAvailability() {' +
'  var styleVal = document.getElementById("bottomStyleValue").value;' +
'  var isAnalog = styleVal === "analog";' +
'  var markerStyle = parseInt(document.getElementById("bigAnalogMarkerStyle").value, 10);' +
'  var override = document.getElementById("bitmapCornerOverride").checked;' +
'  var digitalSidesVal = document.getElementById("digitalSides").value;' +
'  var avail = { upper: false, bottom: false, left: false, right: false, cornersGrayed: false,' +
'    digitalLeft: !isAnalog && (digitalSidesVal === "left" || digitalSidesVal === "both"),' +
'    digitalRight: !isAnalog && (digitalSidesVal === "right" || digitalSidesVal === "both") };' +
'  if (isAnalog) {' +
'    if (markerStyle < 3 || markerStyle === 8 || markerStyle === 9) {' +
'      avail.upper = avail.bottom = avail.left = avail.right = true;' +
'    } else if (markerStyle === 3 || markerStyle === 4 || markerStyle === 6) {' +
'      avail.upper = avail.bottom = true; avail.left = avail.right = override; avail.cornersGrayed = !override;' +
'    } else if (markerStyle === 5) {' +
'      avail.upper = avail.bottom = avail.left = avail.right = true;' +
'    } else if (markerStyle === 7) {' +
'      avail.upper = avail.bottom = avail.left = avail.right = true; avail.cornersGrayed = !override;' +
'    } else {' +
'      avail.upper = true; avail.bottom = avail.left = avail.right = override; avail.cornersGrayed = !override;' +
'    }' +
'  }' +
'  return avail;' +
'}' +
// Updates each slot button\'s label (its example preview value, "OFF",
// or "N/A") and styling to match current settings -- called on init
// and whenever bottom-style/marker-style or a slot\'s own content
// changes.
'function renderSlotPicker() {' +
'  var avail = computeSlotAvailability();' +
'  var isAnalogMode = document.getElementById("bottomStyleValue").value === "analog";' +
'  document.getElementById("slotDiagramClockBar").style.display = isAnalogMode ? "none" : "block";' +
'  document.getElementById("slotBtn-cornerBL").classList.toggle("slot-corner-above-bar", !isAnalogMode);' +
'  document.getElementById("slotBtn-cornerBR").classList.toggle("slot-corner-above-bar", !isAnalogMode);' +
'  for (var key in SLOT_DEFS) {' +
'    var def = SLOT_DEFS[key];' +
'    var btn = document.getElementById(def.btnId);' +
'    var baseClass = btn.getAttribute("data-base-class");' +
'    if (!baseClass) { baseClass = btn.className; btn.setAttribute("data-base-class", baseClass); }' +
    // analogOnly/digitalOnly slots are two different underlying
    // AppMessage fields sharing one settings <select> (see SLOT_DEFS'
    // own comment) but sit at DIFFERENT diagram positions now (the
    // digital ones on the clock bar, the analog ones around the dial)
    // -- only one member of each pair is ever relevant at a time, so
    // the other is fully hidden here rather than shown as a "N/A"
    // placeholder over a spot that mode doesn't even use.
'    if ((def.analogOnly && !isAnalogMode) || (def.digitalOnly && isAnalogMode)) {' +
'      btn.style.display = "none";' +
'      continue;' +
'    }' +
'    btn.style.display = "";' +
'    if (!def.avail(avail)) {' +
'      btn.textContent = "N/A";' +
'      btn.className = baseClass + " slot-na";' +
'      continue;' +
'    }' +
'    var val = parseInt(document.getElementById(def.contentId).value, 10);' +
'    if (!val || !CORNER_PREVIEW_LABELS[val]) {' +
'      btn.textContent = "OFF";' +
'      btn.className = baseClass + " slot-off";' +
'    } else {' +
'      btn.textContent = CORNER_PREVIEW_LABELS[val];' +
'      btn.className = baseClass;' +
'    }' +
'  }' +
'}' +
'function onSlotEditContentChange() {' +
'  setSlotEditorColorGroupVisibility(document.getElementById("slotEditContent").value);' +
'}' +
// Renders the 9 category picker buttons once (their icons/order never
// change at runtime, unlike Content below which is rebuilt per open) --
// called once at page init, see the bottom of this script.
'function renderCategoryButtons() {' +
'  var group = document.getElementById("slotEditCategoryGroup");' +
'  group.innerHTML = CORNER_CATEGORIES.map(function (c) {' +
'    return \'<button type="button" class="category-btn" data-category="\' + c.id + \'" onclick="selectSlotEditCategory(\\\'\' + c.id + \'\\\')" title="\' + c.label + \'">\' + c.icon + \'</button>\';' +
'  }).join("");' +
'}' +
'function updateCategoryButtonActive(categoryId) {' +
'  var buttons = document.getElementById("slotEditCategoryGroup").getElementsByClassName("category-btn");' +
'  for (var i = 0; i < buttons.length; i++) {' +
'    buttons[i].className = "category-btn" + (buttons[i].getAttribute("data-category") === categoryId ? " active" : "");' +
'  }' +
'}' +
'function selectSlotEditCategory(categoryId) {' +
'  document.getElementById("slotEditCategory").value = categoryId;' +
'  updateCategoryButtonActive(categoryId);' +
'  onSlotEditCategoryChange();' +
'}' +
// Repopulates the item dropdown to just the newly-chosen category's
// items whenever the category itself changes -- defaults to that
// category\'s first item, since the previously-selected content id
// (from a different category) is never one of the new options.
// "None" has nothing else to pick, so Content is disabled rather than
// left showing a single always-selected "None" option to interact with.
'function onSlotEditCategoryChange() {' +
'  var categoryId = document.getElementById("slotEditCategory").value;' +
'  var firstItemId = findCategory(categoryId).items[0].id;' +
'  var contentSelect = document.getElementById("slotEditContent");' +
'  contentSelect.innerHTML = categoryItemOptionsHtml(categoryId, firstItemId);' +
'  contentSelect.disabled = (categoryId === "none");' +
'  document.getElementById("slotEditCategoryHelp").style.display = (categoryId === "timezone") ? "" : "none";' +
'  onSlotEditContentChange();' +
'}' +
// Opens the popup pre-filled with this slot\'s current (already-saved)
// content/color -- nothing is written back to the real elements until
// saveSlotEditor() runs, so closing without saving (Cancel, or a tap
// outside the box) leaves the slot exactly as it was.
'function openSlotEditor(slotKey) {' +
'  var def = SLOT_DEFS[slotKey];' +
'  if (!def) return;' +
'  CURRENT_SLOT_KEY = slotKey;' +
'  document.getElementById("slotEditTitle").textContent = def.label;' +
'  var contentVal = document.getElementById(def.contentId).value;' +
'  var colorVal = document.getElementById(def.colorId).value;' +
'  var categoryId = categoryForContentId(contentVal);' +
'  document.getElementById("slotEditCategory").value = categoryId;' +
'  updateCategoryButtonActive(categoryId);' +
'  var contentSelect = document.getElementById("slotEditContent");' +
'  contentSelect.innerHTML = categoryItemOptionsHtml(categoryId, contentVal);' +
'  contentSelect.disabled = (categoryId === "none");' +
'  document.getElementById("slotEditCategoryHelp").style.display = (categoryId === "timezone") ? "" : "none";' +
'  setSlotEditorColorGroupVisibility(contentVal);' +
'  setSlotEditorColorButtons(colorVal);' +
'  document.getElementById("slotEditModal").className = "modal-overlay open";' +
'}' +
'function closeSlotEditor() {' +
'  document.getElementById("slotEditModal").className = "modal-overlay";' +
'  CURRENT_SLOT_KEY = null;' +
'}' +
'function saveSlotEditor() {' +
'  if (!CURRENT_SLOT_KEY) return;' +
'  var def = SLOT_DEFS[CURRENT_SLOT_KEY];' +
'  document.getElementById(def.contentId).value = document.getElementById("slotEditContent").value;' +
'  document.getElementById(def.colorId).value = String(SLOT_EDITOR_DRAFT_COLOR);' +
'  closeSlotEditor();' +
'  renderSlotPicker();' +
'  updateWeatherIconStyleVisibility();' +
'  updatePreview();' +
'}' +
// Weather icon style is now always shown (not gated on any corner/edge
// slot being set to "Weather icon"/"Temp + weather icon" -- previously
// tying visibility to that meant the selector went missing for anyone
// using it on the middle-feature or other content types, or who just
// wanted to preview it in advance). This still refreshes the trigger
// button's own preview/label though -- called from saveSlotEditor() plus
// once at page load, same as before, just no longer touched on slot
// content specifically.
'function clearGrayedSlotsIfUnavailable() {' +
'  var avail = computeSlotAvailability();' +
'  if (avail.cornersGrayed) {' +
'    var cornerIds = ["cornerTL", "cornerTR", "cornerBL", "cornerBR"];' +
'    for (var i = 0; i < cornerIds.length; i++) { document.getElementById(cornerIds[i]).value = "0"; }' +
'  }' +
  // middleLeft/RightLineContent are dual-purpose (digital mode's own
  // side-feature columns reuse these same fields -- see SLOT_DEFS'
  // own comment), and avail.left/right stay false unconditionally in
  // digital mode (it tracks its own availability via
  // avail.digitalLeft/digitalRight instead) -- so this only clears
  // them in analog mode, where !avail.left/right specifically means
  // "this bitmap style doesn't support it without the override",
  // never "wrong mode".
'  var isAnalog = document.getElementById("bottomStyleValue").value === "analog";' +
'  if (isAnalog && !avail.left) {' +
'    document.getElementById("middleLeftLine1Content").value = "0";' +
'    document.getElementById("middleLeftLine2Content").value = "0";' +
'  }' +
'  if (isAnalog && !avail.right) {' +
'    document.getElementById("middleRightLine1Content").value = "0";' +
'    document.getElementById("middleRightLine2Content").value = "0";' +
'  }' +
'}' +
'function applyPresetSlot(n) {' +
'  var jsonEl = document.getElementById("presetSlot" + n + "Json");' +
'  if (!jsonEl || !jsonEl.value) return;' +
'  var obj;' +
'  try { obj = JSON.parse(jsonEl.value); } catch (e) { return; }' +
'  var name = document.getElementById("presetSlot" + n + "Name").value || ("Preset " + n);' +
'  showConfirm("Apply preset", \'Apply "\' + name + \'"? This replaces your current Style, Colors, and Features settings.\', function () {' +
'    applyStyleCornersJson(obj);' +
'  });' +
'}' +
'function savePresetSlot(n) {' +
'  var jsonEl = document.getElementById("presetSlot" + n + "Json");' +
'  var btn = document.getElementById("presetApplyBtn" + n);' +
'  if (!jsonEl) return;' +
'  var name = document.getElementById("presetSlot" + n + "Name").value || ("Preset " + n);' +
'  var hadPreset = !!jsonEl.value;' +
'  showConfirm("Save preset", (hadPreset ? \'Overwrite "\' : \'Save your current design into "\') + name + \'"?\' + (hadPreset ? \' This replaces what was saved there.\' : \'\'), function () {' +
'    jsonEl.value = JSON.stringify(collectStyleCornersJson());' +
'    if (btn) btn.disabled = false;' +
'  });' +
'}' +
'function startRenamePresetSlot(n) {' +
'  var btn = document.getElementById("presetApplyBtn" + n);' +
'  var input = document.getElementById("presetNameInput" + n);' +
'  var nameEl = document.getElementById("presetSlot" + n + "Name");' +
'  if (!input || !btn) return;' +
'  input.value = nameEl ? nameEl.value : ("Preset " + n);' +
'  btn.style.display = "none";' +
'  input.style.display = "";' +
'  input.focus();' +
'  input.select();' +
'}' +
'function commitRenamePresetSlot(n) {' +
'  var btn = document.getElementById("presetApplyBtn" + n);' +
'  var input = document.getElementById("presetNameInput" + n);' +
'  var nameEl = document.getElementById("presetSlot" + n + "Name");' +
'  if (!input || !btn) return;' +
'  var newName = input.value.replace(/^\\s+|\\s+$/g, "") || ("Preset " + n);' +
'  if (nameEl) nameEl.value = newName;' +
'  btn.textContent = newName;' +
'  input.style.display = "none";' +
'  btn.style.display = "";' +
'}' +
'function onAuroraEnabledChange() {' +
'  var enabled = document.getElementById("auroraEnabled").checked;' +
'  var astro = findCategory("astro");' +
'  var hasIt = astro.items.some(function (it) { return it.id === 84; });' +
'  if (enabled && !hasIt) astro.items.push({ id: 84, label: "Aurora Kp index" });' +
'  if (!enabled && hasIt) astro.items = astro.items.filter(function (it) { return it.id !== 84; });' +
'  CONTENT_SELECT_IDS.forEach(function (id) {' +
'    var sel = document.getElementById(id);' +
'    if (!sel) return;' +
'    var opt = sel.querySelector(\'option[value="84"]\');' +
'    if (enabled && !opt) {' +
'      opt = document.createElement("option");' +
'      opt.value = "84";' +
'      opt.textContent = "Aurora Kp index";' +
'      sel.appendChild(opt);' +
'    } else if (!enabled && opt) {' +
'      if (sel.value === "84") sel.value = "0";' + // dangling selection on a now-hidden option -- fall back to None
'      opt.remove();' +
'    }' +
'  });' +
'  renderSlotPicker();' +
'  updatePreview();' +
'}' +
'function countActiveFeatures() {' +
'  var avail = computeSlotAvailability();' +
'  var isAnalogNow = document.getElementById("bottomStyleValue").value === "analog";' +
'  function val(id) { return parseInt(document.getElementById(id).value, 10) || 0; }' +
'  function edgeActive(id, analogFlag, digitalFlag) {' +
'    var usable = isAnalogNow ? analogFlag : digitalFlag;' +
'    return usable && val(id) !== 0;' +
'  }' +
'  var count = 0;' +
'  if (!avail.cornersGrayed) {' +
'    ["cornerTL", "cornerTR", "cornerBL", "cornerBR"].forEach(function (id) { if (val(id) !== 0) count++; });' +
'  }' +
'  if (edgeActive("upperMiddleLine1Content", avail.upper, avail.digitalLeft)) count++;' +
'  if (edgeActive("upperMiddleLine2Content", avail.upper, avail.digitalRight)) count++;' +
'  if (edgeActive("bottomMiddleLine1Content", avail.bottom, true)) count++;' +
'  if (edgeActive("bottomMiddleLine2Content", avail.bottom, false)) count++;' +
'  if (edgeActive("middleLeftLine1Content", avail.left, avail.digitalLeft)) count++;' +
'  if (edgeActive("middleLeftLine2Content", avail.left, avail.digitalLeft)) count++;' +
'  if (edgeActive("middleRightLine1Content", avail.right, avail.digitalRight)) count++;' +
'  if (edgeActive("middleRightLine2Content", avail.right, avail.digitalRight)) count++;' +
'  return count;' +
'}' +
'function computeFeaturesSubheader() {' +
'  var count = countActiveFeatures();' +
'  if (count === 0) return "No features active";' +
'  var fontId = parseInt(document.getElementById("cornerFont").value, 10);' +
'  var fontName = fontLookupEntry(fontId).label;' +
'  return count + " feature" + (count === 1 ? "" : "s") + " active in " + fontName;' +
'}' + ''
// "Planets"/"second hand" here refer to the ON-SHAKE animations
// (Planet seek/Smooth second hand -- see the "On shake animation"
// picker\'s own options), not the separate "Animate background on
// start" picker, per the request\'s own example.
  );
};
