'use strict';

// Runtime fragment extracted from config-page.js.
// The fragment is still generated by PKJS and executed inside the settings page.
module.exports = function buildRuntimeFragment(context) {
  return (
'function canvasFontFor(previewCss, px) {' +
'  var familyMatch = /font-family:\\s*([^;]+);?/.exec(previewCss);' +
'  var family = familyMatch ? familyMatch[1] : "sans-serif";' +
'  var weightMatch = /font-weight:\\s*([^;]+);?/.exec(previewCss);' +
'  var weight = weightMatch ? weightMatch[1].trim() : "400";' +
'  var boldPrefix = (parseInt(weight, 10) >= 600 || weight === "bold") ? "bold " : "";' +
'  var italicPrefix = /font-style:\\s*italic/.test(previewCss) ? "italic " : "";' +
'  return italicPrefix + boldPrefix + px + "px " + family;' +
'}' +

// Runtime copy of this file's own top-level esc() -- needed here since
// renderFontPickerGrid() below builds HTML strings client-side, in the
// webview\'s own separate JS context, which can\'t reach that generator-
// side function.
'function fontLookupEntry(id) {' +
'  id = parseInt(id, 10);' +
'  for (var i = 0; i < FONT_LOOKUP.length; i++) {' +
'    if (FONT_LOOKUP[i].id === id) return FONT_LOOKUP[i];' +
'  }' +
'  return FONT_LOOKUP[0];' +
'}' +
// Scales a font's real on-watch bake size (12-48px) down to something
// that reads clearly inside a compact picker-button preview without
// the biggest ones (the 48px-baked main clock faces) overflowing it --
// same relative ordering as the real sizes (a 12px font\'s preview is
// noticeably smaller than a 48px font\'s), just compressed into a
// roughly 11-26px on-screen range.
'function fontPickerPreviewPx(sizePx) {' +
'  return Math.max(11, Math.min(26, Math.round(sizePx * 0.5)));' +
'}' +

// One entry per font-picker "role" -- which underlying <select> and
// trigger button it drives, whether it\'s restricted to FONT_LOOKUP\'s
// own `mainClock` subset (only the Clock font picker is), whether it
// gets the "Show incompatible fonts" checkbox (only the pickers that
// default to hiding ~48px-scale display fonts do -- see FONT_LOOKUP\'s
// own `small` comment), and what sample text its buttons preview --
// value depends on the picker\'s own role per the request: a clock
// reads a time, a corner/edge feature reads a temperature, and the
// numerals picker reads a number (Roman if that checkbox is on).
'var FONT_PICKER_ROLES = {' +
'  clock: { selectId: "clockFont", triggerId: "clockFontTrigger", title: "Clock font", onlyMainClock: true, showIncompatibleToggle: false,' +
'    previewText: function () { return "12:34"; } },' +
'  cornerFont: { selectId: "cornerFont", triggerId: "cornerFontTrigger", title: "Font", onlyMainClock: false, showIncompatibleToggle: true,' +
'    previewText: function () { return "-10\\u00b0C"; } },' +
'  markerTextFont: { selectId: "markerTextFont", triggerId: "markerTextFontTrigger", title: "Font", onlyMainClock: false, showIncompatibleToggle: false,' +
'    previewText: function () { var roman = document.getElementById("markerTextRoman"); return (roman && roman.checked) ? "XII" : "12"; } }' +
'};' +
'var currentFontPickerRole = null;' +

// Builds whatever goes inside a .font-picker-preview cell for one
// (fontId, role) pair -- a real on-watch rendering (see
// FONT_PREVIEW_IMAGES's own comment) when one exists, the existing
// CSS-approximation text otherwise. Shared by updateFontTriggerLabel()
// and renderFontPickerGrid() below so the two can never fall out of
// sync on which fonts actually have a real image.
'function fontPreviewInnerHtml(fontId, role, text) {' +
'  var images = FONT_PREVIEW_IMAGES[fontId];' +
'  var src = images && images[role];' +
'  var color = fontPreviewColor();' +
'  if (src) {' +
'    var maskCss = "-webkit-mask-image:url(\'" + src + "\'); mask-image:url(\'" + src + "\'); background-color:" + color + ";";' +
'    return \'<span class="font-preview-img" role="img" aria-label="\' + esc(text) + \'" style="\' + maskCss + \'"></span>\';' +
'  }' +
'  return \'<span style="color:\' + color + \';">\' + esc(text) + "</span>";' +
'}' +

// Fills one trigger button\'s own preview/name spans from whatever its
// underlying (now display:none) <select> currently holds -- called
// after every pick, plus once at page load, so the collapsed trigger
// always already shows the current font rendered in itself rather
// than plain placeholder text.
'function updateFontTriggerLabel(role) {' +
'  var cfg = FONT_PICKER_ROLES[role];' +
'  if (!cfg) return;' +
'  var sel = document.getElementById(cfg.selectId);' +
'  var trigger = document.getElementById(cfg.triggerId);' +
'  if (!sel || !trigger) return;' +
'  var entry = fontLookupEntry(sel.value);' +
'  var preview = trigger.querySelector(".font-picker-preview");' +
'  var name = trigger.querySelector(".font-picker-name");' +
'  if (preview) {' +
'    preview.setAttribute("style", entry.preview + " font-size:" + fontPickerPreviewPx(entry.sizePx) + "px;");' +
'    preview.innerHTML = fontPreviewInnerHtml(entry.id, role, cfg.previewText());' +
'  }' +
'  if (name) name.textContent = entry.label;' +
'}' +
'function refreshAllFontTriggerLabels() {' +
'  Object.keys(FONT_PICKER_ROLES).forEach(updateFontTriggerLabel);' +
'}' +

'function openFontPicker(role) {' +
'  currentFontPickerRole = role;' +
'  var cfg = FONT_PICKER_ROLES[role];' +
'  document.getElementById("fontPickerTitle").textContent = cfg.title;' +
'  var incompatibleRow = document.getElementById("fontPickerIncompatibleRow");' +
'  incompatibleRow.style.display = cfg.showIncompatibleToggle ? "" : "none";' +
'  if (cfg.showIncompatibleToggle) {' +
'    var currentId = document.getElementById(cfg.selectId).value;' +
'    document.getElementById("fontPickerShowIncompatible").checked = !fontLookupEntry(currentId).small;' +
'  }' +
'  renderFontPickerGrid();' +
'  document.getElementById("fontPickerModal").className = "modal-overlay open";' +
'}' +
'function closeFontPicker() {' +
'  document.getElementById("fontPickerModal").className = "modal-overlay";' +
'}' +
// Rebuilds the grid for whichever role is currently open -- called on
// open and again whenever "Show incompatible fonts" changes, since
// that changes which entries even appear rather than just their
// styling.
'function renderFontPickerGrid() {' +
'  var cfg = FONT_PICKER_ROLES[currentFontPickerRole];' +
'  if (!cfg) return;' +
'  var sel = document.getElementById(cfg.selectId);' +
'  var currentId = parseInt(sel.value, 10);' +
'  var showIncompatible = cfg.showIncompatibleToggle ? document.getElementById("fontPickerShowIncompatible").checked : true;' +
'  var previewText = cfg.previewText();' +
'  var html = "";' +
'  FONT_LOOKUP.forEach(function (f) {' +
'    if (cfg.onlyMainClock && !f.mainClock) return;' +
'    if (!showIncompatible && !f.small && f.id !== currentId) return;' +
'    var previewStyle = f.preview + " font-size:" + fontPickerPreviewPx(f.sizePx) + "px;";' +
'    html += \'<button type="button" class="font-picker-btn\' + (f.id === currentId ? " selected" : "") + \'" onclick="chooseFontOption(\' + f.id + \')">\' +' +
'      \'<span class="font-picker-preview" style="\' + previewStyle + \'">\' + fontPreviewInnerHtml(f.id, currentFontPickerRole, previewText) + "</span>" +' +
'      \'<span class="font-picker-name">\' + esc(f.label) + "</span></button>";' +
'  });' +
'  document.getElementById("fontPickerGrid").innerHTML = html;' +
'}' +
'function chooseFontOption(id) {' +
'  var cfg = FONT_PICKER_ROLES[currentFontPickerRole];' +
'  if (!cfg) return;' +
'  var sel = document.getElementById(cfg.selectId);' +
'  sel.value = id;' +
'  if (typeof Event === "function") sel.dispatchEvent(new Event("change"));' +
'  else { var evt = document.createEvent("HTMLEvents"); evt.initEvent("change", true, true); sel.dispatchEvent(evt); }' +
'  closeFontPicker();' +
'  refreshAllFontTriggerLabels();' +
'}' +

'function onCornerFontChange() {' +
'  renderSlotPicker();' +
'  updatePreview();' +
'}' +
'function onFontChange() {' +
'  refreshAllFontTriggerLabels();' +
'  onBottomStyleChange();' +
'}' +
''
  );
};
