'use strict';

// Runtime fragment extracted from config-page.js.
// The fragment is still generated by PKJS and executed inside the settings page.
module.exports = function buildRuntimeFragment() {
  return (
'function handAxialPoint(cx, cy, angle, axial) {' +
'  return { x: cx + axial * Math.sin(angle), y: cy - axial * Math.cos(angle) };' +
'}' +
'function handPerpOffset(angle, halfW) {' +
'  return { dx: halfW * Math.cos(angle), dy: halfW * Math.sin(angle) };' +
'}' +
// cfg fields here are already SCALED to canvas px by the caller (see
// readHandConfig()\'s own comment) -- this function itself has no idea
// the watch is really 200x228; it just draws in whatever unit its
// inputs are given in, same as compute_hand_geometry_fp() does with
// its own already-fixed-point inputs.
'function computeHandGeometry(cx, cy, angle, cfg) {' +
'  var len = cfg.length, back = -cfg.backOffset, mid = cfg.middleOffset;' +
'  var halfW = Math.max(0.5, cfg.width / 2), halfSW = Math.max(0.5, cfg.secondaryWidth / 2);' +
'  var polys = [], circles = [];' +
'  function axial(a) { return handAxialPoint(cx, cy, angle, a); }' +
'  function perp(hw) { return handPerpOffset(angle, hw); }' +
'  function capsule(innerAx, outerAx, hw, roundCaps) {' +
'    var inner = axial(innerAx), outer = axial(outerAx), p = perp(hw);' +
'    polys.push([' +
'      { x: inner.x - p.dx, y: inner.y - p.dy }, { x: inner.x + p.dx, y: inner.y + p.dy },' +
'      { x: outer.x + p.dx, y: outer.y + p.dy }, { x: outer.x - p.dx, y: outer.y - p.dy }' +
'    ]);' +
'    if (roundCaps) { circles.push({ x: inner.x, y: inner.y, r: hw }); circles.push({ x: outer.x, y: outer.y, r: hw }); }' +
'  }' +
'  function taper(baseAx, hw, tipPoint) {' +
'    var base = axial(baseAx), p = perp(hw);' +
'    polys.push([{ x: base.x - p.dx, y: base.y - p.dy }, { x: base.x + p.dx, y: base.y + p.dy }, tipPoint]);' +
'  }' +

'  switch (cfg.style) {' +
'    case 1: { var outer = axial(len); taper(back, halfW, outer); break; }' + // triangle

'    case 3: {' + // dauphine
'      var effBack = Math.max(cfg.backOffset, cfg.middleOffset);' +
'      var backTip = axial(-effBack), topTip = axial(len), midPt = axial(mid), p = perp(halfW);' +
'      polys.push([backTip, { x: midPt.x - p.dx, y: midPt.y - p.dy }, topTip, { x: midPt.x + p.dx, y: midPt.y + p.dy }]);' +
'      break;' +
'    }' +
'    case 4: {' + // sword
'      var midAx = Math.min(mid, len);' +
'      var top = axial(len), base = axial(back), midPt = axial(midAx);' +
'      var pw = perp(halfW), psw = perp(halfSW);' +
'      polys.push([' +
'        { x: base.x - pw.dx, y: base.y - pw.dy }, { x: midPt.x - psw.dx, y: midPt.y - psw.dy }, top,' +
'        { x: midPt.x + psw.dx, y: midPt.y + psw.dy }, { x: base.x + pw.dx, y: base.y + pw.dy }' +
'      ]);' +
'      break;' +
'    }' +
'    case 5: capsule(mid, len, halfW, true); capsule(back, mid, halfSW, false); break;' + // pomme

'    case 6: {' + // spade
'      capsule(back, len, halfW, true);' +
'      var tip = axial(len);' +
'      circles.push({ x: tip.x, y: tip.y, r: halfSW });' +
'      var centerAx = (len + back) / 2, apexAx = centerAx + mid;' +
'      if (apexAx > len) {' +
'        var apex = axial(apexAx), psw = perp(halfSW);' +
'        polys.push([{ x: tip.x - psw.dx, y: tip.y - psw.dy }, { x: tip.x + psw.dx, y: tip.y + psw.dy }, apex]);' +
'      }' +
'      break;' +
'    }' +
'    case 7: {' + // arrow
'      var tip = axial(len);' +
'      taper(back, halfW, tip);' +
'      var apex = axial(len + mid), psw = perp(halfSW);' +
'      polys.push([{ x: tip.x - psw.dx, y: tip.y - psw.dy }, { x: tip.x + psw.dx, y: tip.y + psw.dy }, apex]);' +
'      break;' +
'    }' +
'    case 8: {' + // leaf
'      var centerAx = (back + len) / 2, peakAx = centerAx + mid;' +
'      if (peakAx < back) peakAx = back;' +
'      if (peakAx > len) peakAx = len;' +
'      var N = 2;' +
'      var haveBack = peakAx > back, haveTip = peakAx < len;' +
'      var plusA = [], minusA = [], plusB = [], minusB = [];' +
'      if (haveBack) {' +
'        for (var k = 1; k <= N; k++) {' +
'          var u = k / (N + 1), ax = back + (peakAx - back) * u, w = halfW * Math.sin(Math.PI / 2 * u);' +
'          var p = axial(ax), pw = perp(w);' +
'          plusA.push({ x: p.x + pw.dx, y: p.y + pw.dy }); minusA.push({ x: p.x - pw.dx, y: p.y - pw.dy });' +
'        }' +
'      }' +
'      if (haveTip) {' +
'        for (var k = 1; k <= N; k++) {' +
'          var v = k / (N + 1), ax = peakAx + (len - peakAx) * v, w = halfW * Math.cos(Math.PI / 2 * v);' +
'          var p = axial(ax), pw = perp(w);' +
'          plusB.push({ x: p.x + pw.dx, y: p.y + pw.dy }); minusB.push({ x: p.x - pw.dx, y: p.y - pw.dy });' +
'        }' +
'      }' +
'      var peakP = axial(peakAx), pPerp = perp(halfW);' +
'      var peakPlus = { x: peakP.x + pPerp.dx, y: peakP.y + pPerp.dy }, peakMinus = { x: peakP.x - pPerp.dx, y: peakP.y - pPerp.dy };' +
'      var pts = [];' +
'      if (haveBack) { pts.push(axial(back)); for (var i = 0; i < N; i++) pts.push(plusA[i]); }' +
'      pts.push(peakPlus);' +
'      if (haveTip) { for (var i = 0; i < N; i++) pts.push(plusB[i]); pts.push(axial(len)); for (var i = N - 1; i >= 0; i--) pts.push(minusB[i]); }' +
'      pts.push(peakMinus);' +
'      if (haveBack) { for (var i = N - 1; i >= 0; i--) pts.push(minusA[i]); }' +
'      polys.push(pts);' +
'      break;' +
'    }' +
'    case 9: {' + // syringe
'      capsule(back, len, halfW, false);' +
'      var cornerAx = len + mid, taperLen = Math.max(0.5, halfW - halfSW), tipAx = cornerAx + taperLen;' +
'      var corner = axial(cornerAx), tip = axial(tipAx), pw = perp(halfW), psw = perp(halfSW);' +
'      polys.push([' +
'        { x: corner.x - pw.dx, y: corner.y - pw.dy }, { x: corner.x + pw.dx, y: corner.y + pw.dy },' +
'        { x: tip.x + psw.dx, y: tip.y + psw.dy }, { x: tip.x - psw.dx, y: tip.y - psw.dy }' +
'      ]);' +
'      break;' +
'    }' +
'    case 10: {' + // serpentine
'      var SEG = 6;' +
'      var amp = Math.max(0, halfSW - halfW);' +
'      var diameter = Math.abs(cfg.middleOffset); if (diameter < 4) diameter = 4;' +
'      var period = diameter * 2, dirSign = cfg.middleOffset < 0 ? -1 : 1, span = len - back;' +
'      var verts = [];' +
'      for (var i = 0; i <= SEG; i++) {' +
'        var sRel = span * i / SEG, ax = back + sRel;' +
'        var ang = (sRel / period) * 2 * Math.PI;' +
'        var dev = amp * Math.sin(ang) * dirSign;' +
'        var p = axial(ax), pd = perp(dev);' +
'        verts.push({ x: p.x + pd.dx, y: p.y + pd.dy });' +
'      }' +
'      for (var i = 0; i < SEG; i++) {' +
'        var a = verts[i], b = verts[i + 1];' +
'        var tx = b.x - a.x, ty = b.y - a.y, tlen = Math.sqrt(tx * tx + ty * ty);' +
'        var ox, oy;' +
'        if (tlen === 0) { var pd = perp(halfW); ox = pd.dx; oy = pd.dy; }' +
'        else { ox = -ty * halfW / tlen; oy = tx * halfW / tlen; }' +
'        polys.push([{ x: a.x - ox, y: a.y - oy }, { x: a.x + ox, y: a.y + oy }, { x: b.x + ox, y: b.y + oy }, { x: b.x - ox, y: b.y - oy }]);' +
'      }' +
'      break;' +
'    }' +
'    case 0: case 2: default: capsule(back, len, halfW, cfg.style === 0); break;' + // dot / square
'  }' +
'  return { polys: polys, circles: circles };' +
'}' +

'function handPathPolygon(ctx, pts) {' +
'  ctx.beginPath();' +
'  ctx.moveTo(pts[0].x, pts[0].y);' +
'  for (var i = 1; i < pts.length; i++) ctx.lineTo(pts[i].x, pts[i].y);' +
'  ctx.closePath();' +
'}' +
// Approximates fill_polygon_ring_fp()/fill_circle_ring_fp() (an inward
// polygon/circle offset, filled only between the original boundary and
// that offset) with clip+stroke: clip to the exact shape, then stroke
// its own path at 2x the requested thickness -- centered strokes put
// half their width outside the clip (discarded) and half inside,
// leaving exactly a `thickness`-px ring along the inside of the
// boundary, same as the real inset ring.
'function handFillRing(ctx, pathFn, thicknessPx, color) {' +
'  ctx.save();' +
'  pathFn(); ctx.clip();' +
'  pathFn(); ctx.lineWidth = thicknessPx * 2; ctx.strokeStyle = color; ctx.stroke();' +
'  ctx.restore();' +
'}' +
'function handGeometryPaths(geo) {' +
'  return geo.polys.map(function (pts) { return function (ctx) { handPathPolygon(ctx, pts); }; })' +
'    .concat(geo.circles.map(function (c) { return function (ctx) { ctx.beginPath(); ctx.arc(c.x, c.y, Math.max(0, c.r), 0, 2 * Math.PI); }; }));' +
'}' +
// Mirrors draw_hand_shape_from_geometry(): hollow (thickness<=1 = a
// plain 1px stroke, else the inset-ring approximation above) or a
// solid fill, dithering approximated as ~50% opacity throughout this
// preview (same simplification the old placeholder hand preview always
// than a genuine Bayer stipple).
'function drawHandGeometryFill(ctx, geo, color, translucent, hollow, hollowThicknessPx) {' +
'  ctx.globalAlpha = translucent ? 0.5 : 1;' +
'  ctx.fillStyle = color; ctx.strokeStyle = color; ctx.lineWidth = 1;' +
'  handGeometryPaths(geo).forEach(function (pathFn) {' +
'    if (hollow) {' +
'      if (hollowThicknessPx <= 1) { pathFn(ctx); ctx.lineWidth = 1; ctx.stroke(); }' +
'      else handFillRing(ctx, function () { pathFn(ctx); }, hollowThicknessPx, color);' +
'    } else { pathFn(ctx); ctx.fill(); }' +
'  });' +
'  ctx.globalAlpha = 1;' +
'}' +
// Mirrors draw_hand_outline_from_geometry(): a genuine 1px perimeter
// trace, drawn OUTSIDE hollow\'s own inline ring (this is a completely
// separate pass/setting on the watch -- see HandConfig.outline_enabled).
'function drawHandGeometryOutline(ctx, geo, color, translucent) {' +
'  ctx.globalAlpha = translucent ? 0.5 : 1;' +
'  ctx.strokeStyle = color; ctx.lineWidth = 1;' +
'  handGeometryPaths(geo).forEach(function (pathFn) { pathFn(ctx); ctx.stroke(); });' +
'  ctx.globalAlpha = 1;' +
'}' +
// Mirrors draw_hand_shadow_once_fp(): the same geometry, translated by
// shadowDistancePx in shadowAngleDeg\'s direction (a shared light-
// source angle, not rotated with the hand), filled solid or at reduced
// opacity in black -- ~50%/~25% approximating the real ~50%/~25%
// Bayer-dithered density (see that function\'s own threshold comment).
'function drawHandShadow(ctx, cx, cy, angle, cfg, shadowAngleDeg, shadowTranslucentStyle) {' +
'  if (!cfg.shadowEnabled) return;' +
'  var shadowAngleRad = (shadowAngleDeg || 0) * Math.PI / 180;' +
'  var dx = cfg.shadowDistance * Math.sin(shadowAngleRad), dy = -cfg.shadowDistance * Math.cos(shadowAngleRad);' +
'  var geo = computeHandGeometry(cx + dx, cy + dy, angle, cfg);' +
'  ctx.globalAlpha = shadowTranslucentStyle ? (cfg.translucent ? 0.25 : 0.5) : 1;' +
'  ctx.fillStyle = "#000";' +
'  handGeometryPaths(geo).forEach(function (pathFn) { pathFn(ctx); ctx.fill(); });' +
'  ctx.globalAlpha = 1;' +
'}' +
// 0=main, 1=accent, 2=background, 3=none -- same HandConfig.color enum
// handHourColor/handMinColor/handSecColor use. Returns null for "none"
// so callers can skip the fill entirely (see hand_layer_draw()\'s own
// `if (cfg->color != 3)` gate) instead of silently drawing main color.
'function resolveHandPreviewColor(colorVal, colors) {' +
'  if (colorVal === "1") return colors.accent;' +
'  if (colorVal === "2") return colors.bg;' +
'  if (colorVal === "3") return null;' +
'  return colors.text;' +
'}' +
// Reads one hand\'s full HandConfig, scaled from real watch pixels
// (every slider in the editor is a real on-watch px value, 200x228
// screen) into this preview canvas\'s own smaller pixel space via
// `scale` -- length/width/offsets/shadow distance all need it,
// anything already a ratio/flag/enum doesn\'t. Reads the popup\'s own
// LIVE draft fields (hePopupPrefix) while that hand\'s editor is open
// (s_openHandEditorKind), so every slider drag updates the preview in
// real time -- see s_openHandEditorKind\'s own comment -- and the
// committed handHour*/handMin*/handSec* hidden fields otherwise.
'function readHandConfig(kind, scale) {' +
'  var prefix = (s_openHandEditorKind === kind) ? hePopupPrefix(kind) : heHiddenPrefix(kind);' +
'  function num(field, def) { var el = document.getElementById(prefix + field); var v = el ? parseFloat(el.value) : NaN; return isNaN(v) ? def : v; }' +
'  function str(field, def) { var el = document.getElementById(prefix + field); return el ? el.value : def; }' +
'  function bool(field) {' +
'    var el = document.getElementById(prefix + field);' +
'    if (!el) return false;' +
'    return (el.type === "checkbox") ? el.checked : el.value === "true";' +
'  }' +
'  return {' +
'    style: parseInt(str("Style", "0"), 10) || 0,' +
'    width: num("Width", 12) * scale,' +
'    length: num("Length", 51) * scale,' +
'    backOffset: num("BackOffset", 0) * scale,' +
'    middleOffset: num("MiddleOffset", 0) * scale,' +
'    secondaryWidth: num("SecondaryWidth", 6) * scale,' +
'    color: str("Color", "0"),' +
'    outlineEnabled: bool("OutlineEnabled"),' +
'    outlineColor: str("OutlineColor", "0"),' +
'    translucent: bool("Translucent"),' +
'    shadowEnabled: bool("ShadowEnabled"),' +
'    shadowDistance: num("ShadowDistance", 2) * scale,' +
'    hollow: bool("Hollow"),' +
'    hollowThickness: num("HollowThickness", 1) * scale' +
'  };' +
'}' +
// Full hand draw: shadow, then outline (if enabled), then fill (unless
// color is "none") -- same order/gating as hand_layer_draw() itself.
'function drawHandFull(ctx, cx, cy, angle, cfg, colors, shadowAngleDeg, shadowTranslucentStyle) {' +
'  drawHandShadow(ctx, cx, cy, angle, cfg, shadowAngleDeg, shadowTranslucentStyle);' +
'  var geo = computeHandGeometry(cx, cy, angle, cfg);' +
'  if (cfg.outlineEnabled) {' +
'    drawHandGeometryOutline(ctx, geo, resolveHandPreviewColor(cfg.outlineColor, colors) || colors.text, cfg.translucent);' +
'  }' +
'  var fillColor = resolveHandPreviewColor(cfg.color, colors);' +
'  if (fillColor) drawHandGeometryFill(ctx, geo, fillColor, cfg.translucent, cfg.hollow, cfg.hollowThickness);' +
'}' +

// Loaded lazily and cached per style -- base64 data: URIs decode
// effectively instantly in practice, but img.complete is checked
// before drawing rather than assumed, so a not-yet-ready image is
// simply skipped for this tick (the next one, ~1s later via the
// preview\'s own refresh interval, picks it up once ready) instead of
// drawing nothing or throwing.
'var MARKER_PREVIEW_IMG_CACHE = {};' +
'function applyHandPresetToKind(kind, preset) {' +
'  var hp = heHiddenPrefix(kind);' +
'  for (var f in preset) {' +
'    var hidden = document.getElementById(hp + f);' +
'    if (hidden) hidden.value = preset[f];' +
'  }' +
'}' +
// Center circle/Shadow style aren't per-hand (no heHiddenPrefix() to
// go through), and 2 of the 4 fields are sliders whose own displayed
// "Val" span text (see centerCircleModal/shadowStyleModal\'s own HTML)
// only updates from their oninput handler -- setting .value alone from
// here wouldn\'t touch that span, so this sets both by hand for those.
'function applyHandPresetExtras(entry) {' +
'  if (entry.centerCircle) {' +
'    if (entry.centerCircle.Radius !== undefined) {' +
'      document.getElementById("centerCircleRadius").value = entry.centerCircle.Radius;' +
'      var radiusVal = document.getElementById("centerCircleRadiusVal");' +
'      if (radiusVal) radiusVal.textContent = entry.centerCircle.Radius + "px";' +
'    }' +
'    if (entry.centerCircle.Color !== undefined) document.getElementById("centerCircleColor").value = entry.centerCircle.Color;' +
'  }' +
'  if (entry.shadow) {' +
'    if (entry.shadow.Translucent !== undefined) {' +
'      document.getElementById("shadowTranslucent").value = entry.shadow.Translucent;' +
'      refreshModeButtonGroup("shadowTranslucentGroup", "shadowTranslucent");' +
'    }' +
'    if (entry.shadow.Angle !== undefined) {' +
'      document.getElementById("shadowAngle").value = entry.shadow.Angle;' +
'      var angleVal = document.getElementById("shadowAngleVal");' +
'      if (angleVal) angleVal.textContent = entry.shadow.Angle + "\\u00b0";' +
'    }' +
'  }' +
'}' +
// Populates #handStyleGrid with one button per HAND_PRESETS entry --
// called once up front (see the bottom of this script) rather than
// inline in the HTML template, since the button list is entirely
// data-driven off HAND_PRESETS/HAND_STYLE_IMAGES.
'function renderHandStyleGrid() {' +
'  var grid = document.getElementById("handStyleGrid");' +
'  if (!grid) return;' +
'  var html = "";' +
'  for (var n = 1; n <= 9; n++) {' +
'    var entry = HAND_PRESETS[String(n)];' +
'    if (!entry) continue;' +
'    var img = HAND_STYLE_IMAGES[String(n)];' +
'    html += \'<button type="button" class="style-picker-btn" onclick="chooseHandStyle(\' + n + \')">\' +' +
'      (img ? \'<img src="\' + img + \'" alt="\' + entry.title + \'">\' : \'<span class="style-picker-btn-empty">\' + entry.title + "</span>") +' +
'      \'<span class="style-picker-btn-cap-top">\' + entry.title + "</span></button>";' +
'  }' +
'  grid.innerHTML = html;' +
'}' +
'function openHandStyleModal() {' +
'  document.getElementById("handStyleModal").className = "modal-overlay open";' +
'}' +
'function closeHandStyleModal() {' +
'  document.getElementById("handStyleModal").className = "modal-overlay";' +
'}' +
'function chooseHandStyle(n) {' +
'  var entry = HAND_PRESETS[String(n)];' +
'  if (!entry) return;' +
'  applyHandPresetToKind("hour", entry.hour);' +
'  applyHandPresetToKind("min", entry.min);' +
'  applyHandPresetToKind("sec", entry.sec);' +
'  applyHandPresetExtras(entry);' +
'  closeHandStyleModal();' +
'  updateHandStyleButtonLabel();' +
'  refreshEditButtonLabels();' +
'  updatePreview();' +
'}' +
// "Custom" -- same meaning the old dropdown\'s "Custom" option had:
// leaves the hand fields exactly as they are (the 3 "Edit ... hand"
// buttons are always available below regardless), just closes the
// popup without applying any preset. Center circle/shadow are left
// alone too, for the same reason.
'function chooseHandStyleCustom() {' +
'  closeHandStyleModal();' +
'  updateHandStyleButtonLabel();' +
'}' +
// Whether the trigger button reads a preset\'s own name or "Custom" is
// entirely DERIVED from the 3 hands\' current field values, not a
// separate remembered flag -- so it stays correct regardless of HOW
// those values got there (a preset button, a manual "Edit ... hand"
// change, an imported style JSON) without needing every one of those
// call sites to separately remember to update/clear some "current
// preset" state by hand. Deliberately checks only the fields a given
// preset actually specifies (Style/Width/Length/BackOffset/
// MiddleOffset/SecondaryWidth/Color -- see HAND_PRESETS\' own entries)
// rather than every HE_FIELDS entry: those are the fields that define
// the STYLE itself, whereas Translucent/Outline/Shadow/Hollow are
// independent finish options layered on top of it, not part of
// telling one named style apart from another.
'function handKindMatchesPresetFields(kind, presetFields) {' +
'  var hp = heHiddenPrefix(kind);' +
'  for (var f in presetFields) {' +
'    var el = document.getElementById(hp + f);' +
'    if (!el || el.value !== String(presetFields[f])) return false;' +
'  }' +
'  return true;' +
'}' +
'function computeHandStyleLabel() {' +
'  for (var n = 1; n <= 9; n++) {' +
'    var entry = HAND_PRESETS[String(n)];' +
'    if (!entry) continue;' +
'    if (handKindMatchesPresetFields("hour", entry.hour) && handKindMatchesPresetFields("min", entry.min) &&' +
'        handKindMatchesPresetFields("sec", entry.sec)) {' +
'      return entry.title;' +
'    }' +
'  }' +
'  return "Custom";' +
'}' +
'function updateHandStyleButtonLabel() {' +
'  var span = document.getElementById("handStyleTriggerLabel");' +
'  if (span) span.textContent = computeHandStyleLabel();' +
'}' +

// ---- marker style picker popup -----------------------------------------
// Unlike hands, markers keep a real on-watch "which style" field
// (bigAnalogMarkerStyle, still 0-9 -- see eclipse_data.h) -- this
// popup is just a friendlier picker for that same hidden <select>,
// not a replacement for it. MARKER_BITMAP_STYLES covers the 5
// existing bitmap styles (their own thumbnails already exist as
// MARKER_PREVIEW_IMAGES, generated from the actual watch resource
// PNGs -- see generate-marker-previews.js); MARKER_PRESET_STYLES
// covers the 4 procedural ring styles, thumbnails from
// MARKER_PRESET_IMAGES (generate-infographics.js).
'var MARKER_BITMAP_STYLES = [' +
'  { value: "3", title: "Modern" },' +
'  { value: "4", title: "Shadow" },' +
'  { value: "5", title: "Tally" },' +
'  { value: "6", title: "Bell" },' +
'  { value: "7", title: "Fancy" }' +
'];' +
'var MARKER_PRESET_STYLES = [' +
'  { value: "9", title: "None", image: "none" },' +
'  { value: "0", title: "Minimal", image: "minimal" },' +
'  { value: "1", title: "Small", image: "small" },' +
'  { value: "2", title: "Big", image: "big" }' +
'];' +
// Trigger-button label lookup -- every MARKER_BITMAP_STYLES/
// MARKER_PRESET_STYLES entry\'s own title, plus "8" (Custom, the only
// value neither array carries since it has no picker button of its
// own -- see chooseMarkerStyleCustom()).
'var MARKER_STYLE_TITLES = { "8": "Custom" };' +
'MARKER_BITMAP_STYLES.concat(MARKER_PRESET_STYLES).forEach(function (s) { MARKER_STYLE_TITLES[s.value] = s.title; });' +
'function updateHandValLabels(kind) {' +
'  var p = hePopupPrefix(kind);' +
'  ["Width", "Length", "BackOffset", "MiddleOffset", "SecondaryWidth", "ShadowDistance", "HollowThickness"].forEach(function (f) {' +
'    var el = document.getElementById(p + f);' +
'    var out = document.getElementById(p + f + "Val");' +
'    if (el && out) out.textContent = el.value + "px";' +
'  });' +
'}' +
// Shows Middle offset for the 8 styles that use it and Secondary
// width for the 7 that do (see HAND_STYLES_WITH_MIDDLE/
// HAND_STYLES_WITH_SECONDARY) -- independently, since Leaf uses only
// the former. The shared help text tags along with Middle offset
// (the superset of the two).
'function updateHandFieldVisibility(kind) {' +
'  var p = hePopupPrefix(kind);' +
'  var styleEl = document.getElementById(p + "Style");' +
'  if (!styleEl) return;' +
'  var showMiddle = HAND_STYLES_WITH_MIDDLE.indexOf(styleEl.value) !== -1;' +
'  var showSecondary = HAND_STYLES_WITH_SECONDARY.indexOf(styleEl.value) !== -1;' +
'  ["MiddleOffsetRow", "MiddleSecondaryHelp"].forEach(function (id) {' +
'    var el = document.getElementById(p + id);' +
'    if (el) el.style.display = showMiddle ? "" : "none";' +
'  });' +
'  var secEl = document.getElementById(p + "SecondaryWidthRow");' +
'  if (secEl) secEl.style.display = showSecondary ? "" : "none";' +
'  var diagramImg = document.getElementById(p + "Diagram");' +
'  if (diagramImg) {' +
'    var src = HAND_STYLE_DIAGRAM_IMAGES[styleEl.value];' +
'    diagramImg.style.display = src ? "" : "none";' +
'    diagramImg.src = src || "";' +
'  }' +
'  updateHandStyleIconTriggerLabel(p);' +
'}' +
// Fills one editor popup\'s own Shape trigger button from whatever its
// underlying (now display:none) <select> currently holds -- same
// "trigger button mirrors a hidden real control" shape
// updateFontTriggerLabel()/updateColorPresetTriggerLabel() already use
// for their own pickers. Called from updateHandFieldVisibility() above
// so it never needs its own separate call site.
// Fills in the "current status" shown right on each Edit .../Numerals
// trigger button (see this file's own request/comment) -- one shared
// function covering all 7 rather than 7 separate single-purpose ones,
// called after anything that can actually change one of these values:
// saving a hand/indices editor, applying a hand or marker preset,
// tapping a Shadow style/Numerals button, dragging the center circle
// slider, or loading/importing a whole style. A little more than any
// one call site strictly needs, but safer than trying to track exactly
// which of the 7 a given change could touch.
'function refreshEditButtonLabels() {' +
'  ["hour", "min", "sec"].forEach(function (kind) {' +
'    var el = document.getElementById(heHiddenPrefix(kind) + "Style");' +
'    var span = document.getElementById("hand" + kind.charAt(0).toUpperCase() + kind.slice(1) + "StatusLabel");' +
'    if (el && span) span.textContent = HAND_STYLE_NAMES[parseInt(el.value, 10)] || "Baton";' +
'  });' +
'  var ccSpan = document.getElementById("centerCircleStatusLabel");' +
'  var ccEl = document.getElementById("centerCircleRadius");' +
'  if (ccSpan && ccEl) {' +
'    var ccVal = parseInt(ccEl.value, 10) || 0;' +
'    ccSpan.textContent = ccVal > 0 ? (ccVal + "px") : "Off";' +
'  }' +
'  var shSpan = document.getElementById("shadowStyleStatusLabel");' +
'  var shEl = document.getElementById("shadowTranslucent");' +
'  if (shSpan && shEl) shSpan.textContent = shEl.value === "false" ? "Solid" : "Translucent";' +
'  var anyHandShadow = ["hour", "min", "sec"].some(function (kind) {' +
'    var el = document.getElementById(heHiddenPrefix(kind) + "ShadowEnabled");' +
'    return el && el.value === "true";' +
'  });' +
'  var shBtn = document.getElementById("shadowStyleTriggerBtn");' +
'  if (shBtn) shBtn.disabled = !anyHandShadow;' +
'  ["Hour", "Sec"].forEach(function (kindCap) {' +
'    var span = document.getElementById("cm" + kindCap + "StatusLabel");' +
'    var el = document.getElementById("custom" + kindCap + "Style");' +
'    if (el && span) span.textContent = customMarkerStyleLabel(el.value);' +
'  });' +
'  var numSpan = document.getElementById("numeralsStatusLabel");' +
'  var numEl = document.getElementById("markerTextTarget");' +
'  if (numSpan && numEl) numSpan.textContent = markerTextTargetLabel(numEl.value);' +
'}' +
'function updateHandStyleIconTriggerLabel(p) {' +
'  var sel = document.getElementById(p + "Style");' +
'  var trigger = document.getElementById(p + "StyleTrigger");' +
'  if (!sel || !trigger) return;' +
'  var preview = trigger.querySelector(".hand-style-icon-preview");' +
'  var name = trigger.querySelector(".font-picker-name");' +
'  var src = HAND_STYLE_ICON_IMAGES[sel.value];' +
'  if (preview) preview.innerHTML = src ? \'<img src="\' + src + \'" alt="">\' : "";' +
'  if (name) name.textContent = HAND_STYLE_NAMES[parseInt(sel.value, 10)] || "";' +
'}' +
'var HAND_STYLE_ICON_PREFIX = null;' +
'var HAND_STYLE_ICON_KIND = null;' +
'function openHandStyleIconPicker(p, kind) {' +
'  HAND_STYLE_ICON_PREFIX = p;' +
'  HAND_STYLE_ICON_KIND = kind;' +
'  renderHandStyleIconGrid();' +
'  document.getElementById("handStyleIconPickerModal").className = "modal-overlay open";' +
'}' +
'function closeHandStyleIconPicker() {' +
'  document.getElementById("handStyleIconPickerModal").className = "modal-overlay";' +
'}' +
'function renderHandStyleIconGrid() {' +
'  var sel = document.getElementById(HAND_STYLE_ICON_PREFIX + "Style");' +
'  var currentVal = sel ? sel.value : "0";' +
'  var html = "";' +
'  for (var i = 0; i < HAND_STYLE_NAMES.length; i++) {' +
'    var src = HAND_STYLE_ICON_IMAGES[String(i)];' +
'    var selected = String(i) === String(currentVal);' +
'    html += \'<button type="button" class="font-picker-btn\' + (selected ? " selected" : "") + \'" onclick="chooseHandStyleIcon(\' + i + \')">\' +' +
'      \'<span class="font-picker-preview hand-style-icon-preview">\' + (src ? \'<img src="\' + src + \'" alt="">\' : "") + "</span>" +' +
'      \'<span class="font-picker-name">\' + esc(HAND_STYLE_NAMES[i]) + "</span></button>";' +
'  }' +
'  document.getElementById("handStyleIconPickerGrid").innerHTML = html;' +
'}' +
'function chooseHandStyleIcon(value) {' +
'  var sel = document.getElementById(HAND_STYLE_ICON_PREFIX + "Style");' +
'  if (sel) sel.value = value;' +
'  closeHandStyleIconPicker();' +
'  onCustomHandStyleChange(HAND_STYLE_ICON_KIND);' +
'}' +

// Same shape as the hand-style icon picker just above, for
// weather_icon_style\'s own 3 options instead of HandConfig.style\'s 11.
'function updateHandHollowVisibility(kind) {' +
'  var p = hePopupPrefix(kind);' +
'  var box = document.getElementById(p + "Hollow");' +
'  var row = document.getElementById(p + "HollowThicknessRow");' +
'  if (row) row.style.display = (box && box.checked) ? "" : "none";' +
'}' +
'function onHandHollowChange(kind) {' +
'  updateHandHollowVisibility(kind);' +
'  updatePreview();' +
'}' +
'function onCustomHandStyleChange(kind) {' +
'  updateHandFieldVisibility(kind);' +
'  updatePreview();' +
'}' +
// Which hand editor popup (if any) is currently open -- null when
// closed. updatePreview()'s readHandConfig() checks this: for the hand
// currently being edited, it reads the popup's own draft fields
// (hePopupPrefix) so the preview reflects every slider drag/checkbox
// toggle live, per the request; for every other hand (and once this
// one closes, saved or cancelled), it reads the committed handHour*/
// handMin*/handSec* hidden fields instead -- which is also exactly
// what makes Cancel work correctly: an untouched committed value is
// what the preview falls back to the moment the popup closes without
// a Save.
'var s_openHandEditorKind = null;' +
'function onHandSliderInput(kind) {' +
'  updateHandValLabels(kind);' +
'  updatePreview();' +
'}' +
// Pre-fills the popup from the currently-saved handHour*/handMin*/
// handSec* hidden inputs -- nothing is written back until
// saveHandEditor() runs.
'function openHandEditor(kind) {' +
'  s_openHandEditorKind = kind;' +
'  var hp = heHiddenPrefix(kind), p = hePopupPrefix(kind);' +
'  HE_FIELDS.forEach(function (f) {' +
'    var hidden = document.getElementById(hp + f);' +
'    var popupEl = document.getElementById(p + f);' +
'    if (!hidden || !popupEl) return;' +
'    if (HE_CHECKBOX_FIELDS.indexOf(f) !== -1) { popupEl.checked = hidden.value === "true"; } else { popupEl.value = hidden.value; }' +
'  });' +
'  updateHandValLabels(kind);' +
'  updateHandFieldVisibility(kind);' +
'  updateHandHollowVisibility(kind);' +
'  document.getElementById("handEditorModal-" + kind).className = "modal-overlay open";' +
'}' +
'function closeHandEditor(kind) {' +
'  s_openHandEditorKind = null;' +
'  document.getElementById("handEditorModal-" + kind).className = "modal-overlay";' +
'  updatePreview();' +
'}' +
'function saveHandEditor(kind) {' +
'  s_openHandEditorKind = null;' +
'  var hp = heHiddenPrefix(kind), p = hePopupPrefix(kind);' +
'  HE_FIELDS.forEach(function (f) {' +
'    var hidden = document.getElementById(hp + f);' +
'    var popupEl = document.getElementById(p + f);' +
'    if (!hidden || !popupEl) return;' +
'    hidden.value = (HE_CHECKBOX_FIELDS.indexOf(f) !== -1) ? String(popupEl.checked) : popupEl.value;' +
'  });' +
'  closeHandEditor(kind);' +
'  updateHandStyleButtonLabel();' +
'  refreshEditButtonLabels();' +
'  updatePreview();' +
'}' +
// Copies the OTHER hand's last-saved settings into this popup's draft
// controls (not committed until OK) -- direction is fixed per hand, see
// HAND_COPY_SOURCE: hour<-minute, minute<-hour, second<-minute.
'function copyHandConfig(kind) {' +
'  var srcHp = heHiddenPrefix(HAND_COPY_SOURCE[kind]);' +
'  var p = hePopupPrefix(kind);' +
'  HE_FIELDS.forEach(function (f) {' +
'    var src = document.getElementById(srcHp + f);' +
'    var dst = document.getElementById(p + f);' +
'    if (!src || !dst) return;' +
'    if (HE_CHECKBOX_FIELDS.indexOf(f) !== -1) { dst.checked = src.value === "true"; } else { dst.value = src.value; }' +
'  });' +
'  updateHandValLabels(kind);' +
'  updateHandFieldVisibility(kind);' +
'  updateHandHollowVisibility(kind);' +
'}' +
''
  );
};
