'use strict';

// Runtime fragment extracted from config-page.js.
// The fragment is still generated by PKJS and executed inside the settings page.
module.exports = function buildRuntimeFragment() {
  return (
'function getMarkerPreviewImg(styleVal) {' +
'  var src = MARKER_PREVIEW_IMAGES[styleVal];' +
'  if (!src) return null;' +
'  if (!MARKER_PREVIEW_IMG_CACHE[styleVal]) {' +
'    var img = new Image();' +
'    img.src = src;' +
'    MARKER_PREVIEW_IMG_CACHE[styleVal] = img;' +
'  }' +
'  var cached = MARKER_PREVIEW_IMG_CACHE[styleVal];' +
'  return (cached.complete && cached.naturalWidth > 0) ? cached : null;' +
'}' +
'function getTintedMarkerCanvas(styleVal, tintColor) {' +
'  var cacheKey = styleVal + "|" + tintColor;' +
'  if (MARKER_TINT_CACHE[cacheKey]) return MARKER_TINT_CACHE[cacheKey];' +
'  var img = getMarkerPreviewImg(styleVal);' +
'  if (!img) return null;' +
'  var iw = img.naturalWidth, ih = img.naturalHeight;' +
'  if (!iw || !ih) return null;' +
'  try {' +
'    var off = document.createElement("canvas");' +
'    off.width = iw; off.height = ih;' +
'    var octx = off.getContext("2d");' +
'    octx.drawImage(img, 0, 0, iw, ih);' +
'    var imageData = octx.getImageData(0, 0, iw, ih);' +
'    var rgb = hexToRgb(tintColor);' +
'    var data = imageData.data;' +
'    for (var i = 0; i < data.length; i += 4) {' +
'      if (data[i + 3] > 0) {' +
'        data[i] = rgb.r;' +
'        data[i + 1] = rgb.g;' +
'        data[i + 2] = rgb.b;' +
'      }' +
'    }' +
'    octx.putImageData(imageData, 0, 0);' +
'    MARKER_TINT_CACHE[cacheKey] = off;' +
'    return off;' +
'  } catch (e) {' +
'    return null;' +
'  }' +
'}' +
// Draws the tinted mask stretched to fill (w, h). Returns whether it
// actually drew anything, so the caller can fall back to a
// placeholder when no preview image exists yet for this style.
'function drawTintedMarkerBitmap(ctx, styleVal, w, h, tintColor) {' +
'  var tinted = getTintedMarkerCanvas(styleVal, tintColor);' +
'  if (!tinted) return false;' +
'  ctx.drawImage(tinted, 0, 0, w, h);' +
'  return true;' +
'}' +

// ---- marker ring preview -------------------------------------------------
// Direct port of background_layer.c's point_on_ring_fp()/point_on_ring():
// blends a point on a circle of radius reach(pct) with a point on a
// screen-proportioned rectangle of the same reach along its dominant
// axis, by eccentricityPct (0=circle, 100=rectangle). w/h here are this
// canvas\'s own pixel dimensions -- the same 200:228 aspect ratio the
// real watch screen has (see the canvas element\'s own width/height), so
// the ratios this function relies on come out identical without any
// separate scale factor the way hand lengths need.
'function markerReach(w, h, pct) {' +
'  var reachMin = Math.min(w / 4, h / 4), reachMax = Math.max(w / 2, h / 2);' +
'  return reachMin + (reachMax - reachMin) * pct / 100;' +
'}' +
'function drawRingMark(ctx, inner, outer, angle, halfThick, style, color, translucent) {' +
'  ctx.globalAlpha = translucent ? 0.5 : 1;' +
'  ctx.fillStyle = color;' +
'  var sinV = Math.sin(angle), cosV = Math.cos(angle);' +
'  if (inner.x === outer.x && inner.y === outer.y) {' +
'    ctx.beginPath(); ctx.arc(inner.x, inner.y, halfThick, 0, 2 * Math.PI); ctx.fill();' +
'    ctx.globalAlpha = 1; return;' +
'  }' +
'  var dxW = halfThick * cosV, dyW = halfThick * sinV;' +
'  var a = inner, b = outer;' +
'  if (style === 2) {' +
'    var ex = halfThick * sinV, ey = halfThick * cosV;' +
'    a = { x: inner.x - ex, y: inner.y + ey }; b = { x: outer.x + ex, y: outer.y - ey };' +
'  }' +
'  ctx.beginPath();' +
'  ctx.moveTo(a.x - dxW, a.y - dyW); ctx.lineTo(a.x + dxW, a.y + dyW);' +
'  ctx.lineTo(b.x + dxW, b.y + dyW); ctx.lineTo(b.x - dxW, b.y - dyW); ctx.closePath();' +
'  ctx.fill();' +
'  if (style === 0) {' +
'    ctx.beginPath(); ctx.arc(inner.x, inner.y, halfThick, 0, 2 * Math.PI); ctx.fill();' +
'    ctx.beginPath(); ctx.arc(outer.x, outer.y, halfThick, 0, 2 * Math.PI); ctx.fill();' +
'  }' +
'  ctx.globalAlpha = 1;' +
'}' +
// Direct port of draw_marker_ring() (no startup-animation handling --
// nothing here to preview, the watch\'s own marks always settle at
// their final positions almost immediately). cfg: {style, thickness,
// innerEccentricity, outerEccentricity, innerBorderPct, outerBorderPct,
// translucent, color}. skipStep mirrors the C call\'s own use (5, for
// the 60-mark second ring, to skip the marks that coincide with hour
// positions) -- 0 means "skip none".
'function drawMarkerRing(ctx, cx, cy, w, h, cfg, marks, skipStep, colors) {' +
'  if (!cfg || !cfg.thickness) return;' +
'  var color = resolveHandPreviewColor(String(cfg.color), colors) || colors.text;' +
'  var innerPct = cfg.innerBorderPct, outerPct = Math.max(cfg.innerBorderPct, cfg.outerBorderPct);' +
'  var halfThick = Math.max(0.5, cfg.thickness / 2);' +
'  for (var i = 0; i < marks; i++) {' +
'    if (skipStep > 0 && i % skipStep === 0) continue;' +
'    var angle = i * 2 * Math.PI / marks;' +
'    var outer = pointOnRing(cx, cy, w, h, angle, outerPct, cfg.outerEccentricity);' +
'    var inner = pointOnRing(cx, cy, w, h, angle, innerPct, cfg.innerEccentricity);' +
'    drawRingMark(ctx, inner, outer, angle, halfThick, cfg.style, color, cfg.translucent);' +
'  }' +
'}' +
// Matches MARKER_STYLE_HOUR_PRESETS/MARKER_STYLE_SECOND_PRESETS in
// background_layer.c exactly (style/thickness/eccentricity/border by
// index 0=minimal, 1=small, 2=big) -- used for bigAnalogMarkerStyle 0-2.
'var MARKER_STYLE_HOUR_PRESETS = [' +
'  { style: 1, thickness: 1, innerEccentricity: 0, outerEccentricity: 0, innerBorderPct: 65, outerBorderPct: 85, translucent: false, color: 0 },' +
'  { style: 1, thickness: 1, innerEccentricity: 0, outerEccentricity: 0, innerBorderPct: 60, outerBorderPct: 85, translucent: false, color: 0 },' +
'  { style: 2, thickness: 5, innerEccentricity: 0, outerEccentricity: 0, innerBorderPct: 60, outerBorderPct: 85, translucent: false, color: 0 }' +
'];' +
'var MARKER_STYLE_SECOND_PRESETS = [' +
'  { style: 1, thickness: 0, innerEccentricity: 0, outerEccentricity: 0, innerBorderPct: 65, outerBorderPct: 85, translucent: false, color: 0 },' +
'  { style: 1, thickness: 1, innerEccentricity: 0, outerEccentricity: 0, innerBorderPct: 65, outerBorderPct: 85, translucent: false, color: 0 },' +
'  { style: 1, thickness: 1, innerEccentricity: 0, outerEccentricity: 0, innerBorderPct: 65, outerBorderPct: 85, translucent: false, color: 0 }' +
'];' +
// Reads the customHour*/customSec* hidden fields into a cfg object in
// drawMarkerRing()\'s own shape, same field-per-field mapping
// customMarkerHiddenInputsHtml() writes them with.
'function readCustomMarkerConfig(kind) {' +
'  var p = "custom" + (kind === "hour" ? "Hour" : "Sec");' +
'  function v(f) { var el = document.getElementById(p + f); return el ? el.value : null; }' +
'  return {' +
'    style: parseInt(v("Style"), 10) || 0,' +
'    thickness: parseFloat(v("Thickness")) || 0,' +
'    innerEccentricity: parseFloat(v("InnerEcc")) || 0,' +
'    outerEccentricity: parseFloat(v("OuterEcc")) || 0,' +
'    innerBorderPct: parseFloat(v("InnerBorder")) || 0,' +
'    outerBorderPct: parseFloat(v("OuterBorder")) || 0,' +
'    translucent: v("Translucent") === "true",' +
'    color: parseInt(v("Color"), 10) || 0' +
'  };' +
'}' +
// Direct port of draw_text_markers() -- only ever called for the
// custom marker style (bigAnalogMarkerStyle 8), same as on the watch.
// hourCfg/secCfg are whichever MarkerRingConfig-shaped objects the
// caller is currently using for those two rings (preset or custom),
// since text markers piggyback on that ring\'s own innerBorderPct/
// innerEccentricity to decide where the numeral sits.
'function drawTextMarkers(ctx, cx, cy, w, h, colors) {' +
'  var target = document.getElementById("markerTextTarget").value;' +
'  if (target === "0") return;' +
'  var isHour = target === "1";' +
'  var ring = isHour ? readCustomMarkerConfig("hour") : readCustomMarkerConfig("sec");' +
'  var mask = parseInt(document.getElementById(isHour ? "markerTextHourMask" : "markerTextSecMask").value, 10) || 0;' +
'  if (!mask) return;' +
'  var fontSel = document.getElementById("markerTextFont");' +
'  var opt = fontSel.options[fontSel.selectedIndex];' +
'  var roman = document.getElementById("markerTextRoman").checked;' +
'  var offsetPx = parseFloat(document.getElementById("markerTextOffset").value) || 0;' +
'  var scale = w / 200;' +
'  ctx.font = canvasFontFor(opt.getAttribute("data-preview") || "", 14 * scale);' +
'  ctx.fillStyle = colors.text;' +
'  ctx.textAlign = "center"; ctx.textBaseline = "middle";' +
'  for (var i = 0; i < 12; i++) {' +
'    if (!(mask & (1 << i))) continue;' +
'    var angle = i * 2 * Math.PI / 12;' +
'    var offsetPct = Math.max(0, Math.min(100, ring.innerBorderPct + offsetPx));' +
'    var pos = pointOnRing(cx, cy, w, h, angle, offsetPct, ring.innerEccentricity);' +
'    var label = isHour ? (i === 0 ? 12 : i) : i * 5;' +
'    var text = roman ? (label > 0 ? romanNumeral(label) : "") : String(label);' +
'    ctx.fillText(text, pos.x, pos.y);' +
'  }' +
'}' +

'function onMarkerStyleChange() {' +
'  var val = document.getElementById("bigAnalogMarkerStyle").value;' +
'  document.getElementById("customMarkerSection").style.display = (val === "8") ? "" : "none";' +
'  var isBitmap = (val === "3" || val === "4" || val === "5" || val === "6" || val === "7");' +
'  document.getElementById("bitmapMarkerTransparentRow").style.display = isBitmap ? "" : "none";' +
'  document.getElementById("bitmapCornerOverrideRow").style.display = (isBitmap && val !== "5") ? "" : "none";' +
'  document.getElementById("bitmapCornerOverrideHelp").style.display = (isBitmap && val !== "5") ? "" : "none";' +
'  updateMarkerStyleButtonLabel();' +
'  clearGrayedSlotsIfUnavailable();' +
'  renderSlotPicker();' +
'  updatePreview();' +
'}' +
// The 4 corner content selections -- and, since the "Incompatible
// features" override now covers them too, left/right middle-edge
// content -- are off by default (and cleared, not just visually
// grayed) for bitmap styles whose artwork doesn't leave room for them.
// Without this, a value picked while a procedural/custom style (or
// the override) was active would silently keep being sent to the
// watch even once its slot button shows "N/A", since features_layer.c
// no longer suppresses any of this itself (see its own note on why
// that moved here).
'function updateCustomMarkerValLabels(kind) {' +
'  var p = cmPopupPrefix(kind);' +
'  ["Thickness", "InnerEcc", "OuterEcc", "InnerBorder", "OuterBorder"].forEach(function (f) {' +
'    var el = document.getElementById(p + f);' +
'    var out = document.getElementById(p + f + "Val");' +
'    if (el && out) out.textContent = el.value + (f === "Thickness" ? "px" : "%");' +
'  });' +
'}' +
'function onCustomMarkerSliderInput(kind) {' +
'  updateCustomMarkerValLabels(kind);' +
'}' +
'function onCustomMarkerBorderInput(kind, isInner) {' +
'  var p = cmPopupPrefix(kind);' +
'  var innerEl = document.getElementById(p + "InnerBorder"), outerEl = document.getElementById(p + "OuterBorder");' +
'  var innerVal = parseInt(innerEl.value, 10), outerVal = parseInt(outerEl.value, 10);' +
'  outerEl.min = innerVal;' +
'  if (outerVal < innerVal) outerEl.value = innerVal;' +
'  updateCustomMarkerValLabels(kind);' +
'}' +
// Pre-fills the popup from the currently-saved customHour*/customSec*
// hidden inputs -- nothing is written back until saveCustomMarkerEditor()
// runs, so Cancel (or tapping outside) leaves the saved config untouched.
'function openCustomMarkerEditor(kind) {' +
'  var hp = cmHiddenPrefix(kind), p = cmPopupPrefix(kind);' +
'  CM_FIELDS.forEach(function (f) {' +
'    var hidden = document.getElementById(hp + f);' +
'    var popupEl = document.getElementById(p + f);' +
'    if (!hidden || !popupEl) return;' +
'    if (CM_CHECKBOX_FIELDS.indexOf(f) !== -1) { popupEl.checked = hidden.value === "true"; } else { popupEl.value = hidden.value; }' +
'  });' +
'  refreshModeButtonGroup(p + "StyleGroup", p + "Style");' +
'  refreshModeButtonGroup(p + "ColorGroup", p + "Color");' +
'  document.getElementById(p + "OuterBorder").min = document.getElementById(p + "InnerBorder").value;' +
'  updateCustomMarkerValLabels(kind);' +
'  document.getElementById("customMarkerModal-" + kind).className = "modal-overlay open";' +
'}' +
'function closeCustomMarkerEditor(kind) {' +
'  document.getElementById("customMarkerModal-" + kind).className = "modal-overlay";' +
'}' +
'function saveCustomMarkerEditor(kind) {' +
'  var hp = cmHiddenPrefix(kind), p = cmPopupPrefix(kind);' +
'  CM_FIELDS.forEach(function (f) {' +
'    var hidden = document.getElementById(hp + f);' +
'    var popupEl = document.getElementById(p + f);' +
'    if (!hidden || !popupEl) return;' +
'    hidden.value = (CM_CHECKBOX_FIELDS.indexOf(f) !== -1) ? String(popupEl.checked) : popupEl.value;' +
'  });' +
'  closeCustomMarkerEditor(kind);' +
'  refreshEditButtonLabels();' +
'  updatePreview();' +
'}' +
'function applyMarkerPreset(kind, name) {' +
'  var p = cmPopupPrefix(kind);' +
'  var preset = MARKER_PRESETS[kind][name];' +
'  if (!preset) return;' +
'  CM_FIELDS.forEach(function (f) {' +
'    var el = document.getElementById(p + f);' +
'    if (!el || preset[f] === undefined) return;' +
'    if (CM_CHECKBOX_FIELDS.indexOf(f) !== -1) { el.checked = preset[f] === true || preset[f] === "true"; } else { el.value = preset[f]; }' +
'  });' +
'  refreshModeButtonGroup(p + "StyleGroup", p + "Style");' +
'  refreshModeButtonGroup(p + "ColorGroup", p + "Color");' +
'  document.getElementById(p + "OuterBorder").min = document.getElementById(p + "InnerBorder").value;' +
'  updateCustomMarkerValLabels(kind);' +
'}' +
// Copies the OTHER ring\'s last-saved (not currently-open-popup-draft)
// config into this popup\'s controls -- text-marker settings are never
// touched here, since hour/second numbers already exclude each other.
'function copyMarkerConfig(kind) {' +
'  var otherKind = kind === "hour" ? "sec" : "hour";' +
'  var otherHiddenPrefix = cmHiddenPrefix(otherKind), p = cmPopupPrefix(kind);' +
'  CM_FIELDS.forEach(function (f) {' +
'    var src = document.getElementById(otherHiddenPrefix + f);' +
'    var dst = document.getElementById(p + f);' +
'    if (!src || !dst) return;' +
'    if (CM_CHECKBOX_FIELDS.indexOf(f) !== -1) { dst.checked = src.value === "true"; } else { dst.value = src.value; }' +
'  });' +
'  document.getElementById(p + "OuterBorder").min = document.getElementById(p + "InnerBorder").value;' +
'  updateCustomMarkerValLabels(kind);' +
'}' +
'function selectMarkerTextTarget(val) {' +
'  selectModeButton("markerTextTargetGroup", "markerTextTarget", val);' +
'  onMarkerTextTargetChange();' +
'  refreshEditButtonLabels();' +
'}' +
'function onMarkerTextTargetChange() {' +
'  var val = document.getElementById("markerTextTarget").value;' +
'  document.getElementById("markerTextOptions").style.display = (val === "0") ? "none" : "";' +
'  document.getElementById("markerTextHourGrid").style.display = (val === "1") ? "" : "none";' +
'  document.getElementById("markerTextSecGrid").style.display = (val === "2") ? "" : "none";' +
'  updatePreview();' +
'}' +
'function onMarkerTextFontChange() {' +
'  var font = document.getElementById("markerTextFont").value;' +
'  var romanBox = document.getElementById("markerTextRoman");' +
'  var romanHelp = document.getElementById("markerTextRomanHelp");' +
'  var incompatible = !!ROMAN_INCOMPATIBLE_FONTS[font];' +
'  romanBox.disabled = incompatible;' +
'  if (incompatible) romanBox.checked = false;' +
'  if (romanHelp) romanHelp.textContent = incompatible ?' +
'    "Not available with this font -- its glyphs don\'t support Roman numerals correctly." :' +
'    "Shows I, II, III... instead of 1, 2, 3... -- independent of the font above.";' +
'  updatePreview();' +
'}' +
'function openTextMarkerEditor() {' +
'  document.getElementById("textMarkerModal").className = "modal-overlay open";' +
'}' +
'function closeTextMarkerEditor() {' +
'  document.getElementById("textMarkerModal").className = "modal-overlay";' +
'}' +
'function toggleMarkBtn(kind, i) {' +
'  var hiddenId = kind === "hour" ? "markerTextHourMask" : "markerTextSecMask";' +
'  var hidden = document.getElementById(hiddenId);' +
'  var mask = parseInt(hidden.value, 10) || 0;' +
'  var btn = document.getElementById("markBtn-" + kind + "-" + i);' +
'  var bit = 1 << i;' +
'  if (mask & bit) { mask &= ~bit; btn.className = "mark-btn"; } else { mask |= bit; btn.className = "mark-btn active"; }' +
'  hidden.value = String(mask);' +
'}' +

// ---- custom hour/minute/second hand popups ----------------------------
'var HE_FIELDS = ["Style", "Width", "Length", "BackOffset", "MiddleOffset", "SecondaryWidth", "Color", "OutlineEnabled", "OutlineColor", "Translucent", "ShadowEnabled", "ShadowDistance", "Hollow", "HollowThickness"];' +
'var HE_CHECKBOX_FIELDS = ["OutlineEnabled", "Translucent", "ShadowEnabled", "Hollow"];' +
// Which HandConfig.style values actually use MiddleOffset -- 0-2
// (dot/triangle/square) ignore it, same as the C side; every other
// style (3-10) uses it. SecondaryWidth is used by the same set MINUS
// Leaf (8), which only has a single Width slider (its own peak is
// always exactly `width` wide -- see hand_layer.c's own comment).
// Drives updateHandFieldVisibility() below.
'var HAND_STYLES_WITH_MIDDLE = ["3", "4", "5", "6", "7", "8", "9", "10"];' +
'var HAND_STYLES_WITH_SECONDARY = ["3", "4", "5", "6", "7", "9", "10"];' +
'var HAND_COPY_SOURCE = { hour: "min", min: "hour", sec: "min" };' +
'function updateMarkerStyleButtonLabel() {' +
'  var span = document.getElementById("markerStyleTriggerLabel");' +
'  if (!span) return;' +
'  var val = document.getElementById("bigAnalogMarkerStyle").value;' +
'  span.textContent = MARKER_STYLE_TITLES.hasOwnProperty(val) ? MARKER_STYLE_TITLES[val] : "Custom";' +
'}' +
'function renderMarkerStyleGrid() {' +
'  var grid = document.getElementById("markerStyleGrid");' +
'  if (!grid) return;' +
'  var html = "";' +
'  MARKER_BITMAP_STYLES.forEach(function (s) {' +
'    var img = MARKER_PREVIEW_IMAGES[s.value];' +
'    html += \'<button type="button" class="style-picker-btn" onclick="chooseMarkerStyle(\\\'\' + s.value + \'\\\')">\' +' +
'      (img ? \'<img class="bitmap-marker-img" src="\' + img + \'" alt="\' + s.title + \'">\' : \'<span class="style-picker-btn-empty">\' + s.title + "</span>") +' +
'      \'<span class="style-picker-btn-cap">\' + s.title + "</span></button>";' +
'  });' +
'  MARKER_PRESET_STYLES.forEach(function (s) {' +
'    var img = MARKER_PRESET_IMAGES[s.image];' +
'    html += \'<button type="button" class="style-picker-btn" onclick="chooseMarkerStyle(\\\'\' + s.value + \'\\\')">\' +' +
'      (img ? \'<img src="\' + img + \'" alt="\' + s.title + \'">\' : \'<span class="style-picker-btn-empty">\' + s.title + "</span>") +' +
'      \'<span class="style-picker-btn-cap">\' + s.title + "</span></button>";' +
'  });' +
'  grid.innerHTML = html;' +
'}' +
'function openMarkerStyleModal() {' +
'  document.getElementById("markerStyleModal").className = "modal-overlay open";' +
'}' +
'function closeMarkerStyleModal() {' +
'  document.getElementById("markerStyleModal").className = "modal-overlay";' +
'}' +
'function chooseMarkerStyle(value) {' +
'  document.getElementById("bigAnalogMarkerStyle").value = value;' +
'  onMarkerStyleChange();' +
'  closeMarkerStyleModal();' +
'}' +
// "Custom" -- sets the underlying select to the real custom value (8)
// so customMarkerSection actually shows, then closes -- same meaning
// the old dropdown\'s "Custom" option had.
'function chooseMarkerStyleCustom() {' +
'  document.getElementById("bigAnalogMarkerStyle").value = "8";' +
'  onMarkerStyleChange();' +
'  closeMarkerStyleModal();' +
'}' +
'function customMarkerStyleLabel(val) {' +
'  return ["Dot", "Line", "Square"][parseInt(val, 10)] || "Dot";' +
'}' +
'function markerTextTargetLabel(val) {' +
'  if (val === "1") return "On hours";' +
'  if (val === "2") return "Every 5s";' +
'  return "Off";' +
'}' +
''
  );
};
