'use strict';

// Runtime fragment extracted from config-page.js.
// The fragment is still generated by PKJS and executed inside the settings page.
module.exports = function buildRuntimeFragment() {
  return (
'function openExampleStyleModal(n) {' +
'  var entry = EXAMPLE_STYLE_PRESETS[String(n)];' +
'  if (!entry) return;' +
'  s_exampleStyleModalSlot = n;' +
'  var img = document.getElementById("exampleStyleModalImg");' +
'  var src = EXAMPLE_STYLE_IMAGES[String(n)];' +
'  img.style.display = src ? "" : "none";' +
'  img.src = src || "";' +
'  document.getElementById("exampleStyleModalTitle").textContent = entry.title || ("Example " + n);' +
'  document.getElementById("exampleStyleModalDesc").textContent = entry.description || "";' +
'  document.getElementById("exampleStyleModal").className = "modal-overlay open";' +
'}' +
'function closeExampleStyleModal() {' +
'  document.getElementById("exampleStyleModal").className = "modal-overlay";' +
'  s_exampleStyleModalSlot = null;' +
'}' +
'function confirmExampleStyleApply() {' +
'  var entry = s_exampleStyleModalSlot != null ? EXAMPLE_STYLE_PRESETS[String(s_exampleStyleModalSlot)] : null;' +
'  closeExampleStyleModal();' +
'  if (entry && entry.preset) applyStyleCornersJson(entry.preset);' +
'}' +
'function findPresetById(id) {' +
'  for (var i = 0; i < COLOR_SCHEMES.length; i++) {' +
'    if (String(COLOR_SCHEMES[i].id) === String(id)) return COLOR_SCHEMES[i];' +
'  }' +
'  return COLOR_SCHEMES[0];' +
'}' +

'function matchingPresetId(colors) {' +
'  for (var i = 0; i < COLOR_SCHEMES.length; i++) {' +
'    var s = COLOR_SCHEMES[i];' +
'    if (s.bg.toLowerCase() === colors.bg.toLowerCase() && s.text.toLowerCase() === colors.text.toLowerCase() && s.accent.toLowerCase() === colors.accent.toLowerCase()) {' +
'      return s.id;' +
'    }' +
'  }' +
'  return null;' +
'}' +
// Mirrors whatever the popup itself would show for the currently
// active entry (a matching preset\'s own two lines, or the "Custom: ..."
// pair when nothing matches) -- called from updateColorRoleButtons()
// above, so it\'s always in sync with the swatches without needing its
// own separate call site at every place colors can change.
'function computePresetsSubheader() {' +
'  var used = 0;' +
'  for (var n = 1; n <= 6; n++) {' +
'    var el = document.getElementById("presetSlot" + n + "Json");' +
'    if (el && el.value) used++;' +
'  }' +
'  return used + " out of 6 presets used";' +
'}' +
''
  );
};
